'use strict';

const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {
	assertNativeAddonLoadable,
	checkNativeAddon,
	IncompatibleNativeAddonError,
	isPointerCompressionRuntime,
	POINTER_COMPRESSION_MARKER,
	scanUndefinedV8Symbols,
} = require('#src/utility/nativeAddonAbi');
const { buildElf64, V8_API_SYMBOLS, NODE_API_SYMBOLS } = require('./fixtures/syntheticElf64.js');

// Shipped for every platform in their npm packages, so they exist on every CI OS
const MODULES = path.join(__dirname, '../../node_modules');
const NODE_API_PREBUILD = path.join(MODULES, 'argon2/prebuilds/linux-x64/argon2.glibc.node');
const V8_API_PREBUILD = path.join(MODULES, 'uWebSockets.js/uws_linux_x64_137.node');
const MACH_O_PREBUILD = path.join(MODULES, 'uWebSockets.js/uws_darwin_arm64_137.node');

const V8_API_ELF = buildElf64(V8_API_SYMBOLS);
const NODE_API_ELF = buildElf64(NODE_API_SYMBOLS);

describe('nativeAddonAbi', () => {
	let root;
	before(() => {
		root = fs.mkdtempSync(path.join(os.tmpdir(), 'native-addon-abi-'));
	});
	after(() => {
		fs.rmSync(root, { recursive: true, force: true });
	});

	let packageCount = 0;
	/** Writes `contents` at `relativePath` inside a fresh package directory; returns the binary's path. */
	function writeAddon(relativePath, contents, { marker = false, configGypi, packageJson = true } = {}) {
		const packageDirectory = path.join(root, `package-${++packageCount}`);
		const file = path.join(packageDirectory, relativePath);
		fs.mkdirSync(path.dirname(file), { recursive: true });
		if (packageJson)
			fs.writeFileSync(
				path.join(packageDirectory, 'package.json'),
				JSON.stringify({ name: `fixture-addon-${packageCount}` })
			);
		if (marker) fs.writeFileSync(path.join(packageDirectory, POINTER_COMPRESSION_MARKER), '');
		fs.writeFileSync(file, contents);
		if (configGypi) {
			const configPath = path.join(packageDirectory, 'build/config.gypi');
			fs.mkdirSync(path.dirname(configPath), { recursive: true });
			fs.writeFileSync(
				configPath,
				`# Do not edit. File was generated by node-gyp's "configure" step\n{\n  "variables": {\n    "v8_enable_pointer_compression": ${configGypi.pointerCompression},\n    "v8_enable_sandbox": 0\n  }\n}\n`
			);
			const binarySeconds = fs.statSync(file).mtimeMs / 1000;
			const configSeconds = binarySeconds + (configGypi.newerThanBinary ? 60 : -60);
			fs.utimesSync(configPath, configSeconds, configSeconds);
		}
		return file;
	}

	it('reads pointer compression from process.config', () => {
		assert.strictEqual(isPointerCompressionRuntime(), process.config.variables.v8_enable_pointer_compression === 1);
	});

	describe('scanUndefinedV8Symbols', () => {
		it('finds no V8 C++ symbols in a real Node-API prebuild', () => {
			assert.deepStrictEqual(scanUndefinedV8Symbols(NODE_API_PREBUILD), { kind: 'scanned', v8SymbolCount: 0 });
		});

		it('finds the V8 C++ symbols of the real uWebSockets.js prebuild', () => {
			const scan = scanUndefinedV8Symbols(V8_API_PREBUILD);
			assert.strictEqual(scan.kind, 'scanned');
			assert.ok(scan.v8SymbolCount > 0, `expected V8 C++ symbols, found ${scan.v8SymbolCount}`);
		});

		it('counts undefined _ZN2v8 and _ZNK2v8 symbols only', () => {
			const file = writeAddon('mixed.node', V8_API_ELF);
			// the defined v8:: symbol, napi_* and node:: (whose mangled name contains "2v8") are not counted
			assert.deepStrictEqual(scanUndefinedV8Symbols(file), { kind: 'scanned', v8SymbolCount: 2 });
		});

		it('reads big-endian ELF64', () => {
			const file = writeAddon('big-endian.node', buildElf64(V8_API_SYMBOLS, { littleEndian: false }));
			assert.deepStrictEqual(scanUndefinedV8Symbols(file), { kind: 'scanned', v8SymbolCount: 2 });
		});

		it('reports an ELF64 without section headers as uninspectable', () => {
			const file = writeAddon('sectionless.node', buildElf64(V8_API_SYMBOLS, { sectionHeaders: false }));
			assert.deepStrictEqual(scanUndefinedV8Symbols(file), { kind: 'uninspectable', detail: 'no section headers' });
		});

		it('reports an ELF64 whose section headers run past the end of the file as uninspectable', () => {
			const file = writeAddon('truncated.node', V8_API_ELF.subarray(0, V8_API_ELF.length - 10));
			assert.deepStrictEqual(scanUndefinedV8Symbols(file), {
				kind: 'uninspectable',
				detail: 'section headers out of bounds',
			});
		});

		it('reports ELF32, Mach-O and non-binary files as not ELF64', () => {
			const elf32 = writeAddon('elf32.node', buildElf64(V8_API_SYMBOLS, { elfClass: 1 }));
			const script = writeAddon('script.node', 'module.exports = {};');
			for (const file of [elf32, script, MACH_O_PREBUILD])
				assert.deepStrictEqual(scanUndefinedV8Symbols(file), { kind: 'not-elf64' }, file);
		});
	});

	describe('checkNativeAddon', () => {
		const verdictOf = (file) => {
			const { loadable, reason } = checkNativeAddon(file);
			return { loadable, reason };
		};

		it('admits a Node-API addon', () => {
			assert.deepStrictEqual(verdictOf(writeAddon('prebuilds/linux-x64/a.node', NODE_API_ELF)), {
				loadable: true,
				reason: 'node-api',
			});
		});

		it('refuses a V8 C++ API prebuild', () => {
			assert.deepStrictEqual(verdictOf(writeAddon('prebuilds/linux-x64/a.node', V8_API_ELF)), {
				loadable: false,
				reason: 'v8-cxx-abi',
			});
		});

		it('admits a V8 C++ API addon whose package carries the pointer-compression marker', () => {
			const file = writeAddon('prebuilds/linux-x64/a.node', V8_API_ELF, { marker: true });
			assert.deepStrictEqual(verdictOf(file), { loadable: true, reason: 'pointer-compression-marker' });
		});

		it('admits a V8 C++ API addon that node-gyp built under a pointer-compression Node', () => {
			const file = writeAddon('build/Release/a.node', V8_API_ELF, { configGypi: { pointerCompression: 1 } });
			assert.deepStrictEqual(verdictOf(file), { loadable: true, reason: 'pointer-compression-build' });
		});

		it('refuses a binary under build/ that is older than its pointer-compression config.gypi', () => {
			// configure ran under the pointer-compression Node, then the compile failed and left the shipped binary
			const file = writeAddon('build/Release/a.node', V8_API_ELF, {
				configGypi: { pointerCompression: 1, newerThanBinary: true },
			});
			assert.deepStrictEqual(verdictOf(file), { loadable: false, reason: 'v8-cxx-abi' });
		});

		it('refuses a binary built under a standard Node', () => {
			const file = writeAddon('build/Release/a.node', V8_API_ELF, { configGypi: { pointerCompression: 0 } });
			assert.deepStrictEqual(verdictOf(file), { loadable: false, reason: 'v8-cxx-abi' });
		});

		it('refuses a prebuild outside build/ even when build/config.gypi records pointer compression', () => {
			const file = writeAddon('prebuilds/linux-x64/a.node', V8_API_ELF, { configGypi: { pointerCompression: 1 } });
			assert.deepStrictEqual(verdictOf(file), { loadable: false, reason: 'v8-cxx-abi' });
		});

		it('refuses an uninspectable ELF64 unless the marker admits it', () => {
			const sectionless = buildElf64(V8_API_SYMBOLS, { sectionHeaders: false });
			assert.deepStrictEqual(verdictOf(writeAddon('a.node', sectionless)), {
				loadable: false,
				reason: 'uninspectable',
			});
			assert.deepStrictEqual(verdictOf(writeAddon('a.node', sectionless, { marker: true })), {
				loadable: true,
				reason: 'pointer-compression-marker',
			});
		});

		it('admits a file that is not a 64-bit ELF', () => {
			assert.deepStrictEqual(verdictOf(MACH_O_PREBUILD), { loadable: true, reason: 'not-elf64' });
		});
	});

	describe('assertNativeAddonLoadable', () => {
		it('throws an IncompatibleNativeAddonError naming the file, the package and the fixes', () => {
			const file = writeAddon('prebuilds/linux-x64/a.node', V8_API_ELF);
			const packageName = `fixture-addon-${packageCount}`;
			let error;
			try {
				assertNativeAddonLoadable(file);
			} catch (thrown) {
				error = thrown;
			}
			assert.ok(error instanceof IncompatibleNativeAddonError, String(error));
			assert.strictEqual(error.name, 'IncompatibleNativeAddonError');
			assert.strictEqual(error.code, 'ERR_DLOPEN_FAILED');
			assert.strictEqual(error.statusCode, 500);
			assert.ok(String(error).startsWith('IncompatibleNativeAddonError: Native addon '), String(error));
			assert.ok(error.message.includes(fs.realpathSync(file)), error.message);
			assert.ok(error.message.includes(`(package ${packageName})`), error.message);
			assert.ok(error.message.includes(`npm rebuild ${packageName} --build-from-source`), error.message);
			assert.ok(error.message.includes('Node-API version'), error.message);
		});

		it('re-checks a refused addon, so adding the marker admits it', () => {
			const file = writeAddon('a.node', V8_API_ELF);
			assert.throws(() => assertNativeAddonLoadable(file), IncompatibleNativeAddonError);
			fs.writeFileSync(path.join(path.dirname(file), POINTER_COMPRESSION_MARKER), '');
			assertNativeAddonLoadable(file);
		});

		it('re-checks an admitted addon once the binary at its path is replaced', () => {
			const file = writeAddon('a.node', NODE_API_ELF);
			assertNativeAddonLoadable(file);
			fs.writeFileSync(file, V8_API_ELF);
			assert.throws(() => assertNativeAddonLoadable(file), IncompatibleNativeAddonError);
		});

		it('applies the rules at the real path of a symlinked addon', function () {
			if (process.platform === 'win32') this.skip(); // creating symlinks needs elevation there
			const unmarked = writeAddon('a.node', V8_API_ELF);
			const link = path.join(path.dirname(writeAddon('a.node', NODE_API_ELF, { marker: true })), 'link.node');
			fs.symlinkSync(unmarked, link);
			assert.throws(() => assertNativeAddonLoadable(link), IncompatibleNativeAddonError);
		});

		it('leaves a missing file to dlopen', () => {
			assertNativeAddonLoadable(path.join(root, 'missing.node'));
		});
	});
});
