export let generic = {
    host: 'http://localhost',
    port: '9925',
    portRest: '9926',
    username: 'admin',
    password: 'admin',
    schema: "northnwd",
    schema_dev: "dev",
    schema_call: "call",
    schema_other: "other",
    schema_another: "another",
    schema_number_string: "123",
    schema_number: 1123,
    files_location: "/../../test/data/integrationTestsCsvs/",
    emps_tb: "employees",
    emps_id: "employeeid",
    ords_tb: "orders",
    ords_id: "orderid",
    ordd_tb: "order_details",
    ordd_id: "orderdetailid",
    prod_tb: "products",
    prod_id: "productid",
    cust_tb: "customers",
    cust_id: "customerid",
    cate_tb: "categories",
    cate_id: "categoryid",
    supp_tb: "suppliers",
    supp_id: "supplierid",
    ship_tb: "shippers",
    ship_id: "shipperid",
    empt_tb: "employeeterritories",
    empt_id: "employeeid",
    terr_tb: "territories",
    terr_id: "territoryid",
    regi_tb: "region",
    regi_id: "regionid",
    user_id: "",
    test_user_name: "test_user",
    role_id: "",
    job_id: "",
    next_request: "",
    "function:getJobId": "",
    cluster_user_role_id: "",
    insert_timestamp: "0",
    csv_tb: "url_csv_data",
    csv_tb_empty: "url_csv_no_data",
    drop_schema: "drop_schema",
    drop_table: "drop_table",
    s3_key: "",
    s3_secret: ""
}

export const envUrl = generic.host + ':' + generic.port;

export const headers = {
    // Authorization: 'Basic ' + encodeCredentials(),
    // No need to set header content-type as it comes from the server as application/json
    'Content-Type': 'application/json'
}