# HarperDB configuration file. Refer to https://harperdb.io/docs/reference/configuration-file/
---
http:
  compressionThreshold: 0
  cors: false
  corsAccessList:
    - null
  keepAliveTimeout: 30000
  port: 9926
  securePort: null
  mtls: false
  timeout: 120000
threads:
  count: null
  debug: false
authentication:
  cacheTTL: 30000
  enableSessions: true
  operationTokenTimeout: 1d
  refreshTokenTimeout: 30d
analytics:
  aggregatePeriod: 60
clustering:
  enabled: false
  hubServer:
    cluster:
      name: harperdb
      network:
        port: 9932
        routes:
    leafNodes:
      network:
        port: 9931
    network:
      port: 9930
  leafServer:
    network:
      port: 9940
      routes:
    streams:
      maxAge: null
      maxBytes: null
      maxMsgs: null
      maxConsumeMsgs: 100
      maxIngestThreads: 2
      path: null
  logLevel: info
  nodeName: null
  republishMessages: false
  databaseLevel: false
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
    insecure: true
    verify: true
  user: null
componentsRoot: null
localStudio:
  enabled: false
logging:
  auditAuthEvents:
    logFailed: false
    logSuccessful: false
  auditLog: true
  auditRetention: 3d
  file: true
  level: warn
  root: null
  rotation:
    enabled: false
    compress: false
    interval: null
    maxSize: null
    path: null
  stdStreams: false
mqtt:
  network:
    port: 1883
    securePort: 8883
    mtls: false
  webSocket: true
  requireAuthentication: true
operationsApi:
  network:
    cors: true
    corsAccessList:
      - "*"
    domainSocket: hdb/operations-server
    port: 9925
    securePort: null
rootPath: null
storage:
  writeAsync: false
  caching: true
  compression: false
  noReadAhead: true
  path: null
  prefetchWrites: true
tls:
  certificate: null
  certificateAuthority: null
  privateKey: null