# Clone HarperDB node configuration file. Refer to TODO - add ref to config for this
---
databaseConfig:
  excludeDatabases:
    - database: null
  excludeTables:
    - database: null
      table: null
componentConfig:
  skipNodeModules: true
  exclude:
    - name: null
clusteringConfig:
  publishToLeaderNode: true
  subscribeToLeaderNode: true
httpsRejectUnauthorized: false
# harperdb-config values can be used here and will be applied to the clones harperdb-config.yaml file
rootPath: null
operationsApi:
  network:
    port: 9925
clustering:
  nodeName: null
  logLevel: info
logging:
  level: error
