# HarperDB configuration file. Refer to https://harperdb.io/docs/reference/configuration-file/
---
authentication:
  authorizeLocal: true
  cacheTTL: 30000
  enableSessions: true
  operationTokenTimeout: 1d
  refreshTokenTimeout: 30d
analytics:
  aggregatePeriod: 60
clustering:
  enabled: false
  hubServer:
    cluster:
      name: harperdb
      network:
        port: 9932
        routes:
    leafNodes:
      network:
        port: 9931
    network:
      port: 9930
  leafServer:
    network:
      port: 9940
      routes:
    streams:
      maxAge: null
      maxBytes: null
      maxMsgs: null
      path: null
  logLevel: error
  nodeName: null
  republishMessages: true
  databaseLevel: false
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
    insecure: true
    verify: true
  user: null
customFunctions:
  enabled: true
  network:
    cors: false
    corsAccessList:
      - null
    headersTimeout: 60000
    https: false
    keepAliveTimeout: 5000
    port: 9926
    timeout: 120000
  nodeEnv: production
  root: null
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
localStudio:
  enabled: false
logging:
  auditAuthEvents:
    logFailed: false
    logSuccessful: false
  auditLog: true
  auditRetention: 3d
  file: true
  level: warn
  root: null
  rotation:
    enabled: false
    compress: false
    interval: null
    maxSize: null
    path: null
  stdStreams: false
operationsApi:
  foreground: false
  network:
    cors: true
    corsAccessList:
      - "*"
    headersTimeout: 60000
    https: false
    keepAliveTimeout: 5000
    port: 9925
    timeout: 120000
  nodeEnv: production
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
mqtt:
  network:
    port: 1883
    securePort: 8883
  webSocket: true
  requireAuthentication: true
http:
  threads: null
  sessionAffinity: null
rootPath: null
storage:
  writeAsync: false
  caching: true
  compression: false
  noReadAhead: true
  path: null
  prefetchWrites: true
