# HarperDB configuration file. Refer to https://harperdb.io/docs/reference/configuration-file/
---
clustering:
  enabled: false
  hubServer:
    cluster:
      name: harperdb
      network:
        port: 9932
        routes:
    leafNodes:
      network:
        port: 9931
    network:
      port: 9930
  leafServer:
    network:
      port: 9940
      routes:
  nodeName: null
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
    insecure: true
  user: null
customFunctions:
  enabled: true
  network:
    cors: true
    corsAccessList:
      - null
    headersTimeout: 60000
    https: false
    keepAliveTimeout: 5000
    port: 9926
    timeout: 120000
  nodeEnv: production
  root: null
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
ipc:
  network:
    port: 9383
localStudio:
  enabled: false
logging:
  auditLog: false
  file: true
  level: error
  root: null
  rotation:
    compress: false
    dateFormat: YYYY-MM-DD_HH-mm-ss
    maxSize: 10M
    retain: 30
    rotate: false
    rotateInterval: 0 0 * * *
    rotateModule: true
    timezone: GMT
    workerInterval: 30
  stdStreams: false
operationsApi:
  authentication:
    operationTokenTimeout: 1d
    refreshTokenTimeout: 30d
  foreground: false
  network:
    cors: true
    corsAccessList:
      - null
    headersTimeout: 60000
    https: false
    keepAliveTimeout: 5000
    port: 9925
    timeout: 120000
  nodeEnv: production
  tls:
    certificate: null
    certificateAuthority: null
    privateKey: null
http:
  threads: null
rootPath: null
storage:
  writeAsync: false
