'use strict';

const CERTIFICATE_VALUES = {
	cert: '-----BEGIN CERTIFICATE-----\rMIIDXDCCAkSgAwIBAgIFNTE4MzQwDQYJKoZIhvcNAQELBQAwXTEXMBUGA1UEAxMO\rSGFycGVyREIsIEluYy4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDTzEPMA0GA1UE\rBxMGRGVudmVyMRcwFQYDVQQKEw5IYXJwZXJEQiwgSW5jLjAeFw0yMjAzMTEyMzAz\rNDlaFw0yNzAzMTAyMzAzNDlaMF0xFzAVBgNVBAMTDkhhcnBlckRCLCBJbmMuMQsw\rCQYDVQQGEwJVUzELMAkGA1UECBMCQ08xDzANBgNVBAcTBkRlbnZlcjEXMBUGA1UE\rChMOSGFycGVyREIsIEluYy4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\rAQCsEUlBF8WImS78rCFXVKyntxfrW++4qZ3hGnoD2MHZAuDHyeP/5eGnaE9GQhKc\r4DwG4DGvh0wP2zIYnBfiQ3L2ZtnlDR9ZkKIQYGlVxTUn6T43krhK5nZKqDF43Yg3\rZEvO3cbJBjiKZx0eA2/toehdSsTAHHQx5gTDcggNe2tgoJHYPwi9YF/AxSBZrbgb\ryWlYgtYDmF32ytHP03GUCIdKOFuBPsHTGu4SkdEIdLIqO9oglW1YFH5qZ6NiwApW\rsP+GCuqOwDXXbdjr75iq9Tq/CDrjGFLaTPmvd2Q0qG/BtaCll0ghpG+yIHvt/iQs\rajS+LxEWAnVlGMaDdFErbDUtAgMBAAGjIzAhMA8GA1UdEwEB/wQFMAMBAf8wDgYD\rVR0PAQH/BAQDAgIEMA0GCSqGSIb3DQEBCwUAA4IBAQASR4YW/rPK7PNArHVe9zzM\rb0rKNX/2T9/0nybRhmE/+hdlSgliTAeebmwkUS2APckmekYt/q2ZY2NS65Fo/jjp\rG8TJrtcF4h+ylVqUp0ZXQLFtIsr7r2JZA7hJ6njW6G4DHSZ0gxtECLi4CBlTjzm5\rNmnmIDObvGRTuqmcdAZmXeObbta/He2XIzietukPAYX062pNM+G5XT5UM1eG/Vlp\rN86vjhpyI+ffKy+C60SJqxmKM3ydgN7oLscE7+2wLPN25XqN4W99OwGsp5dTdu/f\r5lPtFayXdJ55e/sNQKmGN+UGLrL05c2MWgjb8U/LFilnupUianceoeSERZmVjzKX\r-----END CERTIFICATE-----\r'.replace(
		/\r/g,
		String.fromCharCode(13, 10)
	),
};

const CERTIFICATE_PEM_NAME = 'certificate.pem';
const PRIVATEKEY_PEM_NAME = 'privateKey.pem';
const CA_PEM_NAME = 'caCertificate.pem';

const CERT_NAME = {
	'DEFAULT': 'default',
	'DEFAULT-CA': 'default-ca',
	'SERVER': 'server',
	'CA': 'ca',
	'OPERATIONS-API': 'operations-api',
	'OPERATIONS-CA': 'operations-ca',
};

const CERT_CONFIG_NAME_MAP = {
	tls_certificate: CERT_NAME.SERVER,
	tls_certificateAuthority: CERT_NAME.CA,
	customFunctions_tls_certificate: CERT_NAME.SERVER,
	customFunctions_tls_certificateAuthority: CERT_NAME.CA,
	operationsApi_tls_certificate: CERT_NAME['OPERATIONS-API'],
	operationsApi_tls_certificateAuthority: CERT_NAME['OPERATIONS-CA'],
};

const CERT_PREFERENCE_APP = {
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CERT_PREFERENCE_OPS = {
	[CERT_NAME['OPERATIONS-API']]: 3,
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CERT_PREFERENCE_REP = {
	[CERT_NAME['OPERATIONS-API']]: 3,
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CA_CERT_PREFERENCE_REP = {
	[CERT_NAME['OPERATIONS-CA']]: 3,
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

const CA_CERT_PREFERENCE_OPS = {
	[CERT_NAME['OPERATIONS-CA']]: 3,
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

const CA_CERT_PREFERENCE_APP = {
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

Object.assign(exports, {
	CERTIFICATE_PEM_NAME,
	PRIVATEKEY_PEM_NAME,
	CA_PEM_NAME,
	CERT_NAME,
	CERT_CONFIG_NAME_MAP,
	CERT_PREFERENCE_APP,
	CERT_PREFERENCE_OPS,
	CERT_PREFERENCE_REP,
	CA_CERT_PREFERENCE_REP,
	CA_CERT_PREFERENCE_OPS,
	CA_CERT_PREFERENCE_APP,
	CERTIFICATE_VALUES,
});
