'use strict';

const CERTIFICATE_VALUES = {
	cert: '-----BEGIN CERTIFICATE-----\rMIIDXDCCAkSgAwIBAgIFNTE4MzQwDQYJKoZIhvcNAQELBQAwXTEXMBUGA1UEAxMO\rSGFycGVyREIsIEluYy4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDTzEPMA0GA1UE\rBxMGRGVudmVyMRcwFQYDVQQKEw5IYXJwZXJEQiwgSW5jLjAeFw0yMjAzMTEyMzAz\rNDlaFw0yNzAzMTAyMzAzNDlaMF0xFzAVBgNVBAMTDkhhcnBlckRCLCBJbmMuMQsw\rCQYDVQQGEwJVUzELMAkGA1UECBMCQ08xDzANBgNVBAcTBkRlbnZlcjEXMBUGA1UE\rChMOSGFycGVyREIsIEluYy4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\rAQCsEUlBF8WImS78rCFXVKyntxfrW++4qZ3hGnoD2MHZAuDHyeP/5eGnaE9GQhKc\r4DwG4DGvh0wP2zIYnBfiQ3L2ZtnlDR9ZkKIQYGlVxTUn6T43krhK5nZKqDF43Yg3\rZEvO3cbJBjiKZx0eA2/toehdSsTAHHQx5gTDcggNe2tgoJHYPwi9YF/AxSBZrbgb\ryWlYgtYDmF32ytHP03GUCIdKOFuBPsHTGu4SkdEIdLIqO9oglW1YFH5qZ6NiwApW\rsP+GCuqOwDXXbdjr75iq9Tq/CDrjGFLaTPmvd2Q0qG/BtaCll0ghpG+yIHvt/iQs\rajS+LxEWAnVlGMaDdFErbDUtAgMBAAGjIzAhMA8GA1UdEwEB/wQFMAMBAf8wDgYD\rVR0PAQH/BAQDAgIEMA0GCSqGSIb3DQEBCwUAA4IBAQASR4YW/rPK7PNArHVe9zzM\rb0rKNX/2T9/0nybRhmE/+hdlSgliTAeebmwkUS2APckmekYt/q2ZY2NS65Fo/jjp\rG8TJrtcF4h+ylVqUp0ZXQLFtIsr7r2JZA7hJ6njW6G4DHSZ0gxtECLi4CBlTjzm5\rNmnmIDObvGRTuqmcdAZmXeObbta/He2XIzietukPAYX062pNM+G5XT5UM1eG/Vlp\rN86vjhpyI+ffKy+C60SJqxmKM3ydgN7oLscE7+2wLPN25XqN4W99OwGsp5dTdu/f\r5lPtFayXdJ55e/sNQKmGN+UGLrL05c2MWgjb8U/LFilnupUianceoeSERZmVjzKX\r-----END CERTIFICATE-----\r'.replace(
		/\r/g,
		String.fromCharCode(13, 10)
	),
	key: '-----BEGIN RSA PRIVATE KEY-----\rMIIEowIBAAKCAQEArBFJQRfFiJku/KwhV1Ssp7cX61vvuKmd4Rp6A9jB2QLgx8nj\r/+Xhp2hPRkISnOA8BuAxr4dMD9syGJwX4kNy9mbZ5Q0fWZCiEGBpVcU1J+k+N5K4\rSuZ2SqgxeN2IN2RLzt3GyQY4imcdHgNv7aHoXUrEwBx0MeYEw3IIDXtrYKCR2D8I\rvWBfwMUgWa24G8lpWILWA5hd9srRz9NxlAiHSjhbgT7B0xruEpHRCHSyKjvaIJVt\rWBR+amejYsAKVrD/hgrqjsA1123Y6++YqvU6vwg64xhS2kz5r3dkNKhvwbWgpZdI\rIaRvsiB77f4kLGo0vi8RFgJ1ZRjGg3RRK2w1LQIDAQABAoIBAQCEOmh78EOpnGZC\rYBjjHrvrysVD5gvLcfVUtl8Ls7gMB60re1eOIF+PoZZCHKZnDd6zPfiQtj1adg0C\rYnnsM/8VoaZS4gm0b3RLd3ubIQifWhuo40RissY2yxfxlPSH9LhZCY8ojnJG0cTL\resK579E8WCfopjUY33XLqEbN7Ylv39J+DSqInjqV3efJZUa+HqUJ98VxxzodcKMD\rP3bwUU4gHoSSp4pAsOFH5sQhaIWH1IcNjrAwpee2cJQuh4G157RRIuuUpagtaEG/\rXJIiAyBguJyu3JQFnIBQF01N5+omJgXYJ1L0m54543/iIRThmF3zDCDgCyUzmOk+\rH6As9fv1AoGBANOpOtOZLSAScjGsgJamT3ceJ2wCa86g2j8Oxu8lJUmUp5s3tA0v\rBFW5O3S4KR1EXwkLMBUMrfFM8YvzHWxsXBI6XV8azGLvyqPHxr65OhmpGYkGZMXu\rn9okgjkqlewnY2I073gvyK7ppX51UL5y9fF1vlsk+UlW+Rgx/vMHbdcjAoGBANAc\rxRUsxs4QJpbS4zD3JOkHjr24a97TrS3kCybAHUMpR2NrEHPZw9zex0/aphOJUHfL\rIMkOZdpfDqMfxWy4FAEmqBEMkO2SB+h0Wp4P+qp81ax4vGFiB0cD3wtixr11U1tt\rlZ/ZTdv4VDpDFNK1KaplhTDeyuCjeYfS3/GJia9vAoGAcOsAgjBevZR5rXx84WH6\rVO8WUu37u7FenXNxt9VWTinrPMh72uixZFY8nOk+rely1e1NCn3IMko9Ns9NbDFm\r8SaH95vhXArXTYbfxZIlp9jp0YtCqcHDL+p4Oq04bFMbFyJseu7rHj1x18QYfnHw\rOY/6LL/N6k1m+Hx7qgXVmIcCgYB/w0nTCBw84XlvWqSTqQaF8VfWbWP79mP5KmkW\rLxdH5g2noVEGbohqDnK6OXd/wusdwByukiJBf94Skyy25AOT+VFwthA7aU1ljhkb\rtJ+lDuJ28eBkwLPLCzthWBC+u0qjdJFJAzVjd/7tjcU43nNn4s90AzL12iaAFhvZ\rwyA+DQKBgGc/4cdyGJ3YkcA8150gQBawgJZ7q8V1JND87ggWA8wnK3cHn7rMZQl2\r3emDp9HEFXFex5dbGDDqZFAoesZCDxjknIn9oNfW4PvaWS8q7b6ZKLZG1p03Pu7/\rtYaD0kPbo0kysfFT/co+NgHbdykvIyboomfGdNLTUjYuy6lpwpvs\r-----END RSA PRIVATE KEY-----\r'.replace(
		/\r/g,
		String.fromCharCode(13, 10)
	),
};

const CERTIFICATE_PEM_NAME = 'certificate.pem';
const PRIVATEKEY_PEM_NAME = 'privateKey.pem';
const CA_PEM_NAME = 'caCertificate.pem';
const NATS_CERTIFICATE_PEM_NAME = 'natsCertificate.pem';
const NATS_CA_PEM_NAME = 'natsCaCertificate.pem';

const CERT_NAME = {
	'DEFAULT': 'default',
	'DEFAULT-CA': 'default-ca',
	'SERVER': 'server',
	'CA': 'ca',
	'OPERATIONS-API': 'operations-api',
	'OPERATIONS-CA': 'operations-ca',
};

const CERT_CONFIG_NAME_MAP = {
	tls_certificate: CERT_NAME.SERVER,
	tlsCertificateAuthority: CERT_NAME.CA,
	customFunctions_tls_certificate: CERT_NAME.SERVER,
	customFunctionsTlsCertificateAuthority: CERT_NAME.CA,
	operationsApi_tls_certificate: CERT_NAME['OPERATIONS-API'],
	operationsApiTlsCertificateAuthority: CERT_NAME['OPERATIONS-CA'],
};

const CERT_PREFERENCE_APP = {
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CERT_PREFERENCE_OPS = {
	[CERT_NAME['OPERATIONS-API']]: 3,
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CERT_PREFERENCE_REP = {
	[CERT_NAME['OPERATIONS-API']]: 3,
	[CERT_NAME.SERVER]: 2,
	[CERT_NAME.DEFAULT]: 1,
};

const CA_CERT_PREFERENCE_REP = {
	[CERT_NAME['OPERATIONS-CA']]: 3,
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

const CA_CERT_PREFERENCE_OPS = {
	[CERT_NAME['OPERATIONS-CA']]: 3,
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

const CA_CERT_PREFERENCE_APP = {
	[CERT_NAME.CA]: 2,
	[CERT_NAME['DEFAULT-CA']]: 1,
};

exports.CERTIFICATE_PEM_NAME = CERTIFICATE_PEM_NAME;
exports.PRIVATEKEY_PEM_NAME = PRIVATEKEY_PEM_NAME;
exports.CA_PEM_NAME = CA_PEM_NAME;
exports.CERT_NAME = CERT_NAME;
exports.CERT_CONFIG_NAME_MAP = CERT_CONFIG_NAME_MAP;
exports.CERT_PREFERENCE_APP = CERT_PREFERENCE_APP;
exports.CERT_PREFERENCE_OPS = CERT_PREFERENCE_OPS;
exports.CERT_PREFERENCE_REP = CERT_PREFERENCE_REP;
exports.CA_CERT_PREFERENCE_REP = CA_CERT_PREFERENCE_REP;
exports.CA_CERT_PREFERENCE_OPS = CA_CERT_PREFERENCE_OPS;
exports.CA_CERT_PREFERENCE_APP = CA_CERT_PREFERENCE_APP;
exports.CERTIFICATE_VALUES = CERTIFICATE_VALUES;
exports.NATS_CERTIFICATE_PEM_NAME = NATS_CERTIFICATE_PEM_NAME;
exports.NATS_CA_PEM_NAME = NATS_CA_PEM_NAME;

