name: 🐛 Bug
description: Report broken APIs, performance issues, or other platform problems
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in Harper! Please fill out the template below to help us understand and reproduce the issue.

  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Brief summary of the issue
      placeholder: "Search doesn't work on mobile, navigation menu broken, etc."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: 'What did you expect to happen?'
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'What actually happened instead?'
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device/OS
      description: What device and operating system?
      placeholder: 'Windows 11, macOS 14, iPhone 15, etc.'

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any console errors or network issues? (Check browser dev tools)
      placeholder: 'Copy/paste any error messages from the browser console'

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add screenshots or videos to help explain the problem
      placeholder: 'Drag and drop images here or paste URLs'

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: 'Frequency of issue, workarounds, related issues, etc.'

  - type: dropdown
    id: contribution-intent
    attributes:
      label: Are you planning to fix this issue?
      description: Let us know if you'd like to contribute the fix!
      options:
        - 'No, just reporting the issue'
        - 'Maybe, depending on complexity'
        - "Yes, I'll submit a PR to fix this"
        - "Yes, but I'm a first-time contributor and could use guidance"
    validations:
      required: true

  - type: checkboxes
    id: first-time-contributor
    attributes:
      label: First-time contributor support
      description: Check any that apply (only if you're planning to contribute)
      options:
        - label: I'm new to contributing and would appreciate guidance on the process
        - label: I'd like help understanding the project structure
        - label: I need assistance with setting up the development environment
        - label: I'm comfortable contributing, but new to this project specifically
