ARG NODE_VERSION=22
FROM docker.io/node:${NODE_VERSION} AS builder

ARG HARPERDB_TARBALL

# Change node user and group to harperdb
RUN <<-EOF
    usermod -d /home/harperdb -l harperdb node
    groupmod -n harperdb node
    rm -rf /home/node
EOF

# Copy HarperDB tarball
COPY --chown=harperdb:harperdb ./$HARPERDB_TARBALL /home/harperdb/$HARPERDB_TARBALL

# Create installation directory, .harperdb directory and hdb_boot_properties.file
RUN <<-EOF
    mkdir -p /home/harperdb/hdb
    chown -R harperdb:harperdb /home/harperdb/hdb
    mkdir /home/harperdb/.harperdb
    touch /home/harperdb/.harperdb/hdb_boot_properties.file
    echo 'settings_path = /home/harperdb/hdb/harperdb-config.yaml\ninstall_user = harperdb' > /home/harperdb/.harperdb/hdb_boot_properties.file
    chown -R harperdb:harperdb /home/harperdb/.harperdb
EOF

# Set the user for the below instructions (respected by RUN, CMD, ENTRYPOINT only)
USER harperdb

# Set the  working directory
WORKDIR /home/harperdb/

# Set npm global directory
ENV NPM_CONFIG_PREFIX=/home/harperdb/.npm-global
ENV PATH=/home/harperdb/.npm-global/bin:$PATH

# Install HarperDB package and clean up tarball
RUN <<-EOF
    npm install -g $HARPERDB_TARBALL
    npm cache clean --force
    rm -f $HARPERDB_TARBALL
EOF

FROM docker.io/node:${NODE_VERSION}-slim AS runtime
ARG HARPERDB_VERSION

# Metadata for labels
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_TYPE=git

# For use in labels
ENV SUMMARY="HarperDB is a globally-distributed edge application platform."
ENV DESCRIPTION="HarperDB is a globally-distributed edge application platform comprised of an edge database, streaming broker, and user-defined applications delivering near-zero latency, huge cost savings, and a superior developer experience."

# Useful metadata
LABEL name="harperdb/harperdb"
LABEL vendor="HarperDB"
LABEL version=${HARPERDB_VERSION}
LABEL release=${HARPERDB_VERSION}
LABEL maintainer="support@harperdb.io"
LABEL summary="${SUMMARY}"
LABEL description="${DESCRIPTION}"
LABEL help="https://docs.harperdb.io/"
LABEL url="https://hub.docker.com/r/harperdb/harperdb"
LABEL usage="https://hub.docker.com/r/harperdb/harperdb"

# Set HarperDB installation parameters
ENV TC_AGREEMENT=yes
ENV ROOTPATH=/home/harperdb/hdb
ENV OPERATIONSAPI_NETWORK_PORT=9925
ENV HDB_ADMIN_USERNAME=HDB_ADMIN
ENV HDB_ADMIN_PASSWORD=password
ENV LOGGING_STDSTREAMS=true

USER root
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Install ps and git
RUN <<-EOF
    apt-get update
    apt-get install procps git curl gnupg -y
    mkdir -m 0755 -p /etc/apt/keyrings
    curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /etc/apt/keyrings/google.gpg
    cat <<EOT > /etc/apt/sources.list.d/google.sources
Types: deb
URIs: https://dl.google.com/linux/chrome/deb/
Suites: stable
Components: main
Signed-By: /etc/apt/keyrings/google.gpg
EOT
    apt-get update
    apt-get install google-chrome-stable -y --no-install-recommends
    rm -rf /var/lib/apt/lists/*
EOF

# Add Licensing files
COPY utility/Docker/licenses /licenses

# Create mount point
VOLUME /home/harperdb/hdb

# Expose HarperDB ports
EXPOSE 9925
EXPOSE 9926
EXPOSE 9932
EXPOSE 9933

# Set npm global directory
ENV NPM_CONFIG_PREFIX=/home/harperdb/.npm-global
ENV PATH=/home/harperdb/.npm-global/bin:$PATH

# Change node user and group to harperdb
RUN <<EOF
usermod -d /home/harperdb -l harperdb node
groupmod -n harperdb node
rm -rf /home/node
EOF

# Set the user for the below instructions (respected by RUN, CMD, ENTRYPOINT only)
USER harperdb
COPY --chown=harperdb:harperdb --from=builder /home/harperdb/ /home/harperdb/

# Set the  working directory
WORKDIR /home/harperdb/

# If no arguments are passed to docker run, execute HarperDB
CMD ["harperdb"]