FROM cgr.dev/chainguard/node:latest
ARG HARPERDB_TARBALL

#Expose HarperDB ports
EXPOSE 9925
EXPOSE 9926
EXPOSE 9932

# add Licensing files
RUN mkdir /app/licenses
COPY utility/Docker/licenses/* /app/licenses/.

#Copy HarperDB tarball
COPY ./$HARPERDB_TARBALL /app/.

#Create installation directory, .harperdb directory and hdb_boot_properties.file
RUN mkdir -p /app/hdb && \
  mkdir /home/node/.harperdb && \
  touch /home/node/.harperdb/hdb_boot_properties.file && \
  echo $'settings_path = /app/hdb/harperdb-config.yaml\ninstall_user = node' > /home/node/.harperdb/hdb_boot_properties.file && \
  chown -R node:node /home/node/.harperdb

#Create mount point
VOLUME /app/hdb

#Set HarperDB installation parameters
ENV TC_AGREEMENT=yes
ENV ROOTPATH=/app/hdb
ENV OPERATIONSAPI_NETWORK_PORT=9925
ENV HDB_ADMIN_USERNAME=HDB_ADMIN
ENV HDB_ADMIN_PASSWORD=password
ENV LOGGING_STDSTREAMS=true

#Set the  working directory for the below instructions
WORKDIR /app/

#Install HarperDB package and clean up tarball
RUN npm install $HARPERDB_TARBALL && \
    npm cache clean --force && \
    rm -fv $HARPERDB_TARBALL && \
    ln -s /app/node_modules/.bin/harperdb /app/harperdb

#If no arguments are passed to docker run, execute HarperDB
CMD ["harperdb"]
