FROM registry.access.redhat.com/ubi9/nodejs-18:latest

ARG HARPERDB_TARBALL
ARG HARPERDB_VERSION

# metadata for labels
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_TYPE=git

# for use in labels
ENV SUMMARY="HarperDB is a turn-key solution for the collection, distribution, and analysis of data."
ENV DESCRIPTION="HarperDB is a turn-key solution for the collection, distribution, and analysis of data throughout your organization. Projects that have historically taken months (or even years) of consulting, configuration, and custom development can be completed in days or weeks with HarperDB."

# useful metadata
LABEL name="harperdb/harperdb-openshift"
LABEL vendor="HarperDB"
LABEL version=${HARPERDB_VERSION}
LABEL release=${HARPERDB_VERSION}
LABEL maintainer="support@harperdb.io"
LABEL summary="${SUMMARY}"
LABEL description="${DESCRIPTION}"
LABEL help="https://docs.harperdb.io/docs/"
LABEL url="https://hub.docker.com/r/harperdb/harperdb-openshift"
LABEL usage="https://hub.docker.com/r/harperdb/harperdb-openshift"

# pull from gha build
LABEL build-date="${BUILD_DATE}"
LABEL vcs-ref="${VCS_REF}"
LABEL vcs-type="${VCS_TYPE}"

# inherited labels we need to overwrite
LABEL io.k8s.description="${DESCRIPTION}"
LABEL io.k8s.display-name="HarperDB"
LABEL io.openshift.expose-services="9925:HTTP,9926:HTTP,9932:TCP"
LABEL io.openshift.tags="harperdb"
LABEL com.redhat.component="harperdb-container"

# redhat labels we are allowing throug (except dev-mode.port)
LABEL com.redhat.dev-mode.port="DEBUG_PORT:NA"
# LABEL com.redhat.deployments-dir=""
# LABEL com.redhat.dev-mode=""
# LABEL com.redhat.license_terms=""

# labels we don't want
LABEL io.buildah.version=""
LABEL io.buildpacks.stack.id=""
LABEL io.openshift.s2i.scripts-url=""
LABEL io.s2i.scripts-url=""

#Expose HarperDB ports
EXPOSE 9925
EXPOSE 9926
EXPOSE 9932

# for install only
USER root

# install deps
RUN dnf install --assumeyes hostname && dnf clean all

# RHCC Licensing files
RUN mkdir /licenses
COPY utility/Docker/licenses/* /licenses/.

# Create symlink for compatibility
RUN ln -s ${HOME} /home/harperdb

#Copy HarperDB tarball
COPY $HARPERDB_TARBALL .

#Create installation directory, .harperdb directory and hdb_boot_properties.file
RUN mkdir -p /home/harperdb/hdb && \
    mkdir /home/harperdb/.harperdb && \
    touch /home/harperdb/.harperdb/hdb_boot_properties.file && \
    echo $'settings_path = /home/harperdb/hdb/harperdb-config.yaml\ninstall_user = default' > /home/harperdb/.harperdb/hdb_boot_properties.file

#Create mount point
VOLUME /home/harperdb/hdb

# fix permissions -- requires root group
RUN chown -R default:root /home/harperdb /home/harperdb/.harperdb

#Set HarperDB installation parameters
ENV TC_AGREEMENT=yes
ENV ROOTPATH=/home/harperdb/hdb
ENV OPERATIONSAPI_NETWORK_PORT=9925
ENV HDB_ADMIN_USERNAME=HDB_ADMIN
ENV HDB_ADMIN_PASSWORD=password
ENV LOGGING_STDSTREAMS=true

#Set the user for the below instructions (respected by RUN, CMD, ENTRYPOINT only)
USER default

#Set the  working directory for the below instructions
WORKDIR /home/harperdb/

#Install HarperDB package and clean up tarball
RUN npm install $HARPERDB_TARBALL && \
    npm cache clean --force && \
    rm -f $HARPERDB_TARBALL

#If no arguments are passed to docker run, execute HarperDB
CMD ["harperdb"]