ARG NODE_VERSION
FROM node:$NODE_VERSION-bullseye-slim

ARG HARPERDB_TARBALL
ARG HARPERDB_VERSION

# metadata for labels
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_TYPE=git

# for use in labels
ENV SUMMARY="HarperDB is a globally-distributed edge application platform."
ENV DESCRIPTION="HarperDB is a globally-distributed edge application platform comprised of an edge database, streaming broker, and user-defined applications delivering near-zero latency, huge cost savings, and a superior developer experience."

# useful metadata
LABEL name="harperdb/harperdb"
LABEL vendor="HarperDB"
LABEL version=${HARPERDB_VERSION}
LABEL release=${HARPERDB_VERSION}
LABEL maintainer="support@harperdb.io"
LABEL summary="${SUMMARY}"
LABEL description="${DESCRIPTION}"
LABEL help="https://docs.harperdb.io/"
LABEL url="https://hub.docker.com/r/harperdb/harperdb"
LABEL usage="https://hub.docker.com/r/harperdb/harperdb"

#Expose HarperDB ports
EXPOSE 9925
EXPOSE 9926
EXPOSE 9932

# Install ps
RUN apt-get update && apt-get install -y procps git

# add Licensing files
RUN mkdir /licenses
COPY utility/Docker/licenses/* /licenses/.

#Copy HarperDB tarball
COPY ./$HARPERDB_TARBALL /opt/

#Create mount point
VOLUME /opt/harperdb/

#Set npm global directory
ENV NPM_CONFIG_PREFIX=/opt/.npm-global
ENV PATH=/opt/.npm-global/bin:$PATH

#Set HarperDB installation parameters
ENV TC_AGREEMENT=yes
ENV ROOTPATH=/opt/harperdb/
ENV OPERATIONSAPI_NETWORK_PORT=9925
ENV HDB_ADMIN_USERNAME=HDB_ADMIN
ENV HDB_ADMIN_PASSWORD=password
ENV LOGGING_STDSTREAMS=true

#Set the  working directory for the below instructions
WORKDIR /opt/

#Install HarperDB package and clean up tarball
RUN npm install -g $HARPERDB_TARBALL && \
    npm cache clean --force && \
    rm -f $HARPERDB_TARBALL

#If no arguments are passed to docker run, execute HarperDB
CMD ["harperdb"]