#!/bin/bash


working_dir=$(pwd)
target_dir=$(pwd)/harperdb_cluster
node_count=$2
port_offset=3
http_port=9935
cluster_port=1111


build(){
rm -rf $target_dir/*

while [ $node_count -gt 0 ]
do

mkdir -p $target_dir/node_$node_count/harperdb
mkdir -p $target_dir/node_$node_count/data
rsync -avq $working_dir/* $target_dir/node_$node_count/harperdb --exclude $target_dir
#p -R $working_dir/* $target_dir/node_$node_count/harperdb/

sed -i "s/HDB_PROC_NAME =.*/HDB_PROC_NAME='NoOne';/1" $target_dir/node_$node_count/harperdb/utility/common_utils.js

cd $target_dir/node_$node_count/harperdb/bin

#INSTALL 
node harperdb install --TC_AGREEMENT yes --HDB_ROOT $target_dir/node_$node_count/data/hdb --HTTP_PORT $http_port  --HTTPS_PORT 31283 --HDB_ADMIN_USERNAME admin --HDB_ADMIN_PASSWORD Abc1234! --HDB_REGISTER false

#Update hdb/config/settings.js
#printf  "\nCLUSTERING = TRUE\nCLUSTERING_PORT = %s\nNODE_NAME = node_%s" "$cluster_port" "$node_count" >> $target_dir/node_$node_count/data/hdb/config/settings.js
sed -i "s/CLUSTERING = .*/CLUSTERING = TRUE/" $target_dir/node_$node_count/data/hdb/config/settings.js
sed -i "s/CLUSTERING_PORT.*/CLUSTERING_PORT = $cluster_port/" $target_dir/node_$node_count/data/hdb/config/settings.js
sed -i "s/NODE_NAME.*/NODE_NAME = node_$node_count/" $target_dir/node_$node_count/data/hdb/config/settings.js

sed -i 's/LOG_LEVEL.*/LOG_LEVEL = debug/' $target_dir/node_$node_count/data/hdb/config/settings.js

sed -i 's/ALLOW_SELF_SIGNED_SSL_CERTS = false/ALLOW_SELF_SIGNED_SSL_CERTS=TRUE/' $target_dir/node_$node_count/data/hdb/config/settings.js

#License register
$working_dir/utility/devops/script_register_local.exp $target_dir/node_$node_count/harperdb

#KILL only this node
#kill $(ps -ef | grep "$target_dir/node_$node_count" | awk '{print $2}')

node harperdb run
sleep 10s

#Add Node
$working_dir/node_modules/newman/bin/newman.js run https://api.getpostman.com/collections/4f5d17b0-e923-e7c0-feb9-f80dbcf1764a?apikey=fe1dfb2c3647474f8f3e9d836783e694 --environment https://api.getpostman.com/environments/e8201aee-1a99-7de7-4910-62c0e0e6b755?apikey=fe1dfb2c3647474f8f3e9d836783e694 --folder add_node$node_count

#sleep 5s
#echo "*********************$target_dir/node_$node_count"
#Kill only this node
#kill $(ps -ef | grep "$target_dir/node_$node_count" | awk '{print $2}')


node_count=$(($node_count - 1));
http_port=$(($http_port + $port_offset));
cluster_port=$(($cluster_port + $port_offset));

done
#echo "CLUSTER BUILT NOTHING SHOULD BE RUNNING: $(ps -ef | grep $target_dir)"
#kill $(ps -ef | grep "harperdb_cluster" | awk '{print $2}')

#cd $target_dir/node_1/harperdb/bin/
#node harperdb run

#sleep 7s

#cd $target_dir/node_2/harperdb/bin/
#node harperdb run

#sleep 10s
###########  this was to make sure all the processes were up whn dooing cluster testing among KB and Z. Maybe get rid of this?
################
#procs=$(ps -ef | grep [h]arperdb_cluster| wc -l)
#echo "number of processes $procs"
#while [ "$procs" -lt 34 ] 
#do
#echo "waiting"
#procs=$(ps -ef | grep [h]arperdb_cluster| wc -l)
#echo "****************$procs ****************"
#sleep 5s
#done

#Add Schema
$working_dir/node_modules/newman/bin/newman.js run https://api.getpostman.com/collections/4f5d17b0-e923-e7c0-feb9-f80dbcf1764a?apikey=fe1dfb2c3647474f8f3e9d836783e694 --environment https://api.getpostman.com/environments/e8201aee-1a99-7de7-4910-62c0e0e6b755?apikey=fe1dfb2c3647474f8f3e9d836783e694 --folder create_schema
sleep 2s
#create table and delay request 1000ms btween checking and adding data
$working_dir/node_modules/newman/bin/newman.js run https://api.getpostman.com/collections/4f5d17b0-e923-e7c0-feb9-f80dbcf1764a?apikey=fe1dfb2c3647474f8f3e9d836783e694 --environment https://api.getpostman.com/environments/e8201aee-1a99-7de7-4910-62c0e0e6b755?apikey=fe1dfb2c3647474f8f3e9d836783e694 --folder create_table --delay-request 1000
#check data select by hash
$working_dir/node_modules/newman/bin/newman.js run https://api.getpostman.com/collections/4f5d17b0-e923-e7c0-feb9-f80dbcf1764a?apikey=fe1dfb2c3647474f8f3e9d836783e694 --environment https://api.getpostman.com/environments/e8201aee-1a99-7de7-4910-62c0e0e6b755?apikey=fe1dfb2c3647474f8f3e9d836783e694 --folder data_wait --delay-request 500



echo "DONE"
}

destroy(){
kill $(ps -ef | grep [c]luster/node_ | awk '{print $2}')
rm -rf $target_dir
echo "Target dir empty? $(ls -al $target_dir)"
echo "cluster processess killed? $(ps -ef | grep [n]ode_)"
}

$@

