#!/bin/bash

working_dir=/opt/harperdb
target_dir=/opt/harperdb_cluster
node_count=$2
port_offset=3
http_port=9925
cluster_port=1111


build(){
rm -rf $target_dir/*

while [ $node_count -gt 0 ]
do

mkdir -p $target_dir/node_$node_count/harperdb
mkdir -p $target_dir/node_$node_count/data
cp -R $working_dir/* $target_dir/node_$node_count/harperdb/

sed -i "/HDB_PROC_NAME/ s/ =.*/ = 'no_oneis_here';/" $target_dir/node_$node_count/harperdb/bin/run.js

cd $target_dir/node_$node_count/harperdb/bin
node harperdb.js install --TC_AGREEMENT yes --HDB_ROOT $target_dir/node_$node_count/data/hdb --HTTP_PORT $http_port  --HTTPS_PORT 31283 --HDB_ADMIN_USERNAME admin --HDB_ADMIN_PASSWORD Abc1234! --HDB_REGISTER false

printf  "\nCLUSTERING = TRUE\nCLUSTERING_PORT = %s\nNODE_NAME = node_%s" "$cluster_port" "$node_count" >> $target_dir/node_$node_count/data/hdb/config/settings.js

node harperdb run

/opt/harperdb/utility/devops/script_register.exp $target_dir/node_$node_count/harperdb

node harperdb.js run

node_count=$(($node_count - 1));
http_port=$(($http_port + $port_offset));
cluster_port=$(($cluster_port + $port_offset));

done

echo "DONE"
}

destroy(){
kill $(ps -ef | grep [c]luster/node_ | awk '{print $2}')
rm -rf $target_dir/*
echo "Targe dir empty? $(ls -al $target_dir)"
echo "cluster processess killed? $(ps -ef | grep [n]ode_)"
}

$@

