services:
  harper1:
    extends:
      service: harper
      file: utility/dev/docker-compose.base.yml
    networks:
      harperdb:
        ipv4_address: 10.99.25.10
    environment:
      REPLICATION_HOSTNAME: 10.99.25.10
      REPLICATION_PORT: 10.99.25.10:9933
      REPLICATION_ROUTES: '["ws://10.99.25.20:9933", "ws://10.99.25.30:9933"]'
    ports:
      - "49925:9925"
      - "49926:9926"
  harper2:
    extends:
      service: harper
      file: utility/dev/docker-compose.base.yml
    networks:
      harperdb:
        ipv4_address: 10.99.25.20
    environment:
      REPLICATION_HOSTNAME: 10.99.25.20
      REPLICATION_PORT: 10.99.25.20:9933
      REPLICATION_ROUTES: '["ws://10.99.25.10:9933", "ws://10.99.25.30:9933"]'
    ports:
      - "49935:9925"
      - "49936:9926"
  harper3:
    extends:
      service: harper
      file: utility/dev/docker-compose.base.yml
    networks:
      harperdb:
        ipv4_address: 10.99.25.30
    environment:
      REPLICATION_HOSTNAME: 10.99.25.30
      REPLICATION_PORT: 10.99.25.30:9933
      REPLICATION_ROUTES: '["ws://10.99.25.10:9933", "ws://10.99.25.20:9933"]'
    ports:
      - "49945:9925"
      - "49946:9926"
networks:
  harperdb:
    ipam:
      config:
        - subnet: 10.99.25.0/24
