import { stripFencedBlocks } from './prFormatLinks.mjs';
import { isTrivialChange } from './reviewGate.mjs';

const NON_MEMBER_ASSOCIATIONS = new Set([
	'COLLABORATOR',
	'CONTRIBUTOR',
	'FIRST_TIME_CONTRIBUTOR',
	'FIRST_TIMER',
	'MANNEQUIN',
	'NONE',
]);

/** Blank fenced blocks so a PR that DOCUMENTS these markers is not classified by its own example.
 *  Shares the format checker's stripper, which handles the CRLF, `~~~`, 4+-backtick, indented and
 *  blockquoted forms a web-edited body produces. */
const withoutFences = (body) => stripFencedBlocks(String(body ?? ''));

// `Complexity:` must carry a real grade — a hand-written PR whose description says
// "Complexity: O(n log n)" is not an agent PR.
const AI_FIELD =
	/^[ \t]*(?:<sub>[ \t]*)?(?:Complexity[ \t]*:[ \t]*(?:easy|medium|complicated)\b|(?:Review-Coverage|Human-Review-Need)[ \t]*:)/im;
const AI_TOOL = '(?:claude|codex|(?:chat)?gpt|openai|anthropic|gemini|grok|cursor|composer|copilot|devin|aider)';
// Every agent harness signs the body it generates. Measured over two weeks of harper and
// harper-pro PRs, 14 of the 15 member PRs carrying no HEG field carried this signature — so
// keying AI-authorship on the fields alone exempts most of the population it is meant to cover.
//
// Anchored to the start of a line and required to name a tool, in both directions: a mid-sentence
// "the stubs were generated by Gemini last quarter" is prose, not a signature; a signature naming
// two tools ("Generated with Cursor Grok") still counts, which `generatorFamily` would not.
const AI_SIGNATURE = new RegExp(`^[ \\t>*_]*(?:\u{1F916}\\s*)?generated (?:with|by)\\b[^\\n]*\\b${AI_TOOL}\\b`, 'imu');
const AI_COAUTHOR = new RegExp(`^[ \\t>]*Co-Authored-By:[^\\n]*\\b${AI_TOOL}\\b`, 'imu');

export function isAiAuthored(body) {
	const text = withoutFences(body);
	return AI_FIELD.test(text) || AI_SIGNATURE.test(text) || AI_COAUTHOR.test(text);
}

const COMPLEXITY = /^[ \t]*(?:<sub>[ \t]*)?Complexity[ \t]*:[ \t]*([A-Za-z]+)/gim;

/** The LAST field wins, like the coverage footer. A body that kept round one's `easy` above round
 *  two's `complicated` would otherwise waive on the grade its author had already withdrawn. */
export const declaredComplexity = (body) =>
	[...withoutFences(body).matchAll(COMPLEXITY)].at(-1)?.[1]?.toLowerCase() ?? '';

/** The field is written by the agent grading its own work, and pr-conventions guarantees it may
 *  only RAISE the diff-derived grade — so the diff has to corroborate a waiver, not just the claim. */
export const EASY_MAX_LINES = 150;
export const EASY_MAX_FILES = 10;

export function easyDiffWaiver(pr, { maxLines = EASY_MAX_LINES, maxFiles = EASY_MAX_FILES } = {}) {
	if (declaredComplexity(pr?.body) !== 'easy') return { claimed: false, waived: false, lines: 0 };
	const lines = (Number(pr?.additions) || 0) + (Number(pr?.deletions) || 0);
	const sized = Number.isFinite(pr?.additions) && Number.isFinite(pr?.deletions);
	const files = Number(pr?.changed_files);
	const counted = Number.isInteger(files) && files > 0;
	const reason = !sized
		? 'GitHub reported no line counts for this PR'
		: !counted
			? 'GitHub reported no changed-file count for this PR'
			: lines > maxLines
				? `${lines} changed lines exceeds ${maxLines}`
				: files > maxFiles
					? `${files} changed files exceeds ${maxFiles}`
					: '';
	return { claimed: true, waived: !reason, reason, lines, files: counted ? files : 0, maxLines, maxFiles };
}

export function classifyPullRequest(pr) {
	const login = String(pr?.user?.login ?? '');
	const association = String(pr?.author_association ?? '');
	// Missing size fields must not read as 0+0 and silently exempt every PR.
	const sized = Number.isFinite(pr?.additions) && Number.isFinite(pr?.deletions);
	const exempt =
		login.endsWith('[bot]') || pr?.user?.type === 'Bot'
			? 'bot author'
			: NON_MEMBER_ASSOCIATIONS.has(association)
				? `author is not an org member (${association}) — always human review`
				: sized && isTrivialChange(pr.additions, pr.deletions)
					? 'trivial change (≤2 lines)'
					: '';
	return { exempt, draft: Boolean(pr?.draft), sized };
}
