const assert = require('node:assert');
const { X509Certificate } = require('node:crypto');

const testUtils = require('../../testUtils.js');
testUtils.preTestPrep();

// Ed25519 pair generated by integrationTests/utils/security/ocsp/generate-test-certs.ts:
// LEAF (CN=Valid Client) is issued directly by CA (CN=Harper Test CA).
const CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBJTCB2KADAgECAgEBMAUGAytlcDAyMTAwFQYDVQQDDA5IYXJwZXIgVGVzdCBD
QTAXBgNVBAoMEEhhcnBlciBPQ1NQIFRlc3QwHhcNMjYwOTAxMjE0NzQ0WhcNMjcw
OTAxMjE0NzQ0WjAyMTAwFQYDVQQDDA5IYXJwZXIgVGVzdCBDQTAXBgNVBAoMEEhh
cnBlciBPQ1NQIFRlc3QwKjAFBgMrZXADIQA/ARiyM3Gz7K9HuO+LmHGxsCGvMszu
mxpDkr58EhthKqMTMBEwDwYDVR0TAQH/BAUwAwEB/zAFBgMrZXADQQCs/xR0lkdu
nO45pdieb8dsjRo/wcjx0O+xDAN4QtH7j4CpNQsyHvJzNJgODee9hVzH5LBufx0f
6im/vfIBngkJ
-----END CERTIFICATE-----`;
const LEAF_PEM = `-----BEGIN CERTIFICATE-----
MIIBajCCARygAwIBAgIBAzAFBgMrZXAwMjEwMBUGA1UEAwwOSGFycGVyIFRlc3Qg
Q0EwFwYDVQQKDBBIYXJwZXIgT0NTUCBUZXN0MB4XDTI2MDkwMTIxNDc0NFoXDTI3
MDkwMTIxNDc0NFowMDEuMBMGA1UEAwwMVmFsaWQgQ2xpZW50MBcGA1UECgwQSGFy
cGVyIE9DU1AgVGVzdDAqMAUGAytlcAMhAI9RNJ+274/TIvRG53cZb9g/Uj+WsQ7I
67J8vRkz83YHo1kwVzAMBgNVHRMBAf8EAjAAMDIGCCsGAQUFBwEBBCYwJDAiBggr
BgEFBQcwAYYWaHR0cDovLzEyNy4wLjAuMToxODA4MDATBgNVHSUEDDAKBggrBgEF
BQcDAjAFBgMrZXADQQDTP/KnPnD9wkVAkgzIid3d9uE8Mw1I+vmF389amqDUWDO7
qCv4tBFlJOXtP1Ky4nVswGNtB6aZTR0hRgFo8koJ
-----END CERTIFICATE-----`;
// Unrelated EC authority (CN=Test Client CA)
const FOREIGN_CA_PEM = `-----BEGIN CERTIFICATE-----
MIICQDCCAeagAwIBAgIJAMKXQ+J63NsdMAoGCCqGSM49BAMCMBkxFzAVBgNVBAMM
DlRlc3QgQ2xpZW50IENBMB4XDTI2MDkwMTIxNDE0MFoXDTI2MTAwMTIxNDE0MFow
GTEXMBUGA1UEAwwOVGVzdCBDbGllbnQgQ0EwggFLMIIBAwYHKoZIzj0CATCB9wIB
ATAsBgcqhkjOPQEBAiEA/////wAAAAEAAAAAAAAAAAAAAAD///////////////8w
WwQg/////wAAAAEAAAAAAAAAAAAAAAD///////////////wEIFrGNdiqOpPns+u9
VXaYhrxlHQawzFOw9jvOPD4n0mBLAxUAxJ02CIbnBJNqZnjhE50mt4GffpAEQQRr
F9Hy4SxCR/i85uVjpEDydwN9gS3rM6D0oTlF2JjClk/jQuL+Gn+bjufrSnwPnhYr
zjNXazFezsu2QGg3v1H1AiEA/////wAAAAD//////////7zm+q2nF56E87nKwvxj
JVECAQEDQgAEcfl1glwYMF5z5W129RIaTEQ0nA2U99CQJgQif+87N1k4uc6vk8Wj
oIt7ZaHtdToxKiOitlu62+axbMTLHL5gp6MjMCEwDwYDVR0TAQH/BAUwAwEB/zAO
BgNVHQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIgIxwFYypo7Ot7jI+cJy61
5aVc/l1f9NOHtzkb2QMulToCIQCbIO7EWDQrupVV7x1mwYZcqMaYM3bkzveiwclk
lGwVZQ==
-----END CERTIFICATE-----`;

const leaf = new X509Certificate(LEAF_PEM);
const ca = new X509Certificate(CA_PEM);

// A second run of the same generator: identical subject DN to CA_PEM, different Ed25519 key.
const IMPOSTOR_CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBJTCB2KADAgECAgEBMAUGAytlcDAyMTAwFQYDVQQDDA5IYXJwZXIgVGVzdCBD
QTAXBgNVBAoMEEhhcnBlciBPQ1NQIFRlc3QwHhcNMjYwOTAxMjIwOTUyWhcNMjcw
OTAxMjIwOTUyWjAyMTAwFQYDVQQDDA5IYXJwZXIgVGVzdCBDQTAXBgNVBAoMEEhh
cnBlciBPQ1NQIFRlc3QwKjAFBgMrZXADIQAhnqXMevRsmAh0/I/b7cXyOTLq5d0R
kNkavAk+d83rR6MTMBEwDwYDVR0TAQH/BAUwAwEB/zAFBgMrZXADQQBOJ0gM1Ays
lG5ztYAnkbahGmI6Y4/Cg0/LOEoUWRK2YjL4NKpUYVL5w8fvyeJIZJgwV/LEkPS+
AHQYE+IRj6cL
-----END CERTIFICATE-----`;

describe('certificateVerification/trustedIssuers.ts', function () {
	let trustedIssuers;

	before(function () {
		trustedIssuers = require('#src/security/certificateVerification/trustedIssuers');
	});

	afterEach(function () {
		trustedIssuers.publishTrustedAuthorities([]);
	});

	it('resolves nothing before any authorities are published', function () {
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(leaf.raw), undefined);
	});

	it('resolves the issuer of a leaf signed by a published authority', function () {
		trustedIssuers.publishTrustedAuthorities([FOREIGN_CA_PEM, CA_PEM]);
		const issuer = trustedIssuers.resolveTrustedIssuer(leaf.raw, leaf.fingerprint256);
		assert.ok(Buffer.isBuffer(issuer));
		assert.ok(issuer.equals(ca.raw));
	});

	it('splits a PEM bundle into individual authorities', function () {
		trustedIssuers.publishTrustedAuthorities([`${FOREIGN_CA_PEM}\n${CA_PEM}\n`]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw).equals(ca.raw));
	});

	it('accepts TRUSTED CERTIFICATE and X509 CERTIFICATE PEM labels and skips non-string values', function () {
		const relabel = (label) =>
			CA_PEM.replace('BEGIN CERTIFICATE', `BEGIN ${label}`).replace('END CERTIFICATE', `END ${label}`);
		trustedIssuers.publishTrustedAuthorities([undefined, 42, relabel('TRUSTED CERTIFICATE')]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw).equals(ca.raw));
		trustedIssuers.publishTrustedAuthorities([relabel('X509 CERTIFICATE')]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw).equals(ca.raw));
	});

	it('never resolves a certificate as its own issuer', function () {
		trustedIssuers.publishTrustedAuthorities([CA_PEM]);
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(ca.raw, ca.fingerprint256), undefined);
	});

	it('does not resolve an authority that did not issue the leaf', function () {
		trustedIssuers.publishTrustedAuthorities([FOREIGN_CA_PEM]);
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(leaf.raw), undefined);
	});

	it('rejects a same-subject authority whose key did not sign the leaf', function () {
		const impostor = new X509Certificate(IMPOSTOR_CA_PEM);
		assert.strictEqual(
			leaf.checkIssued(impostor),
			true,
			'impostor must pass the name-only check for this test to mean anything'
		);
		trustedIssuers.publishTrustedAuthorities([IMPOSTOR_CA_PEM]);
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(leaf.raw), undefined);
	});

	it('skips unparseable authorities and still resolves from the rest', function () {
		trustedIssuers.publishTrustedAuthorities([
			'-----BEGIN CERTIFICATE-----\nbm90IGEgY2VydGlmaWNhdGU=\n-----END CERTIFICATE-----',
			'not even pem',
			CA_PEM,
		]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw).equals(ca.raw));
	});

	it('returns undefined for an unparseable leaf', function () {
		trustedIssuers.publishTrustedAuthorities([CA_PEM]);
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(Buffer.from('garbage')), undefined);
	});

	it('drops cached resolutions when a new authority set is published', function () {
		trustedIssuers.publishTrustedAuthorities([CA_PEM]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw, leaf.fingerprint256));
		trustedIssuers.publishTrustedAuthorities([FOREIGN_CA_PEM]);
		assert.strictEqual(trustedIssuers.resolveTrustedIssuer(leaf.raw, leaf.fingerprint256), undefined);
		trustedIssuers.publishTrustedAuthorities([CA_PEM]);
		assert.ok(trustedIssuers.resolveTrustedIssuer(leaf.raw, leaf.fingerprint256));
	});
});
