on:
  push:
    branches:
      - "CORE-1771"
  workflow_call:
    outputs:
      nodeVersion: 
        value: ${{jobs.getNodeVersion.outputs.nodeVersion}}
      harperdbVersion: 
        value: ${{jobs.getNodeVersion.outputs.harperdbVersion}}
      goVersion: 
        value: ${{jobs.getNodeVersion.outputs.goVersion}}
  workflow_dispatch:
name: Build
jobs:
  getNodeVersion:
    runs-on: ubuntu-latest
    outputs:
      nodeVersion: ${{ steps.getNode.outputs.NODE_VERSION }}
      harperdbVersion: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
      goVersion: ${{ steps.getNode.outputs.GO_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - id: getnode
      name: Get node version
      run: |
        pwd
        NODE_VERSION="$(cat package.json | jq -r '.engines."preferred-node"')"
        HARPERDB_VERSION=$(cat package.json | jq -r '.version')
        GO_VERSION=$(cat package.json | jq -r '.engines."go-lang"')
        echo "::set-output name=NODE_VERSION::$NODE_VERSION"
        echo "::set-output name=HARPERDB_VERSION::$HARPERDB_VERSION"
        echo "::set-output name=GO_VERSION::$GO_VERSION"
  build:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ needs.getNodeVersion.outputs.nodeVersion }}
    - name: Build artifact
      run: |
        #!/bin/bash
        whoami
        ./utility/devops/build/all-in-one-build.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: harperdb-${{ needs.getNodeVersion.outputs.harperdbVersion }}.tgz
        path: harperdb-${{ needs.getNodeVersion.outputs.harperdbVersion }}.tgz
        retention-days: 1