on:
  workflow_call:
    outputs:
      nodeVersion: 
        value: ${{jobs.getNodeVersion.outputs.nodeVersion}}
      harperdbVersion: 
        value: ${{jobs.getNodeVersion.outputs.harperdbVersion}}
  workflow_dispatch:
name: Build
jobs:
  getNodeVersion:
    runs-on: ubuntu-latest
    #runs-on: fabric-dev-runner
    outputs:
      nodeVersion: ${{ steps.getNode.outputs.NODE_VERSION }}
      harperdbVersion: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - id: getnode
      name: Get node version
      run: |
        pwd
        NODE_VERSION="$(node --version)"
        NODE_VERSION="${NODE_VERSION:1}"
        HARPERDB_VERSION=$(cat package.json | jq -r '.version')
        echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "HARPERDB_VERSION=$HARPERDB_VERSION" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    #runs-on: fabric-dev-runner
    needs: getNodeVersion
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ needs.getNodeVersion.outputs.nodeVersion }}
    - name: Build artifact
      run: |
        #!/bin/bash
        ./utility/devops/build/build.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: harperdb-${{ needs.getNodeVersion.outputs.harperdbVersion }}.tgz
        path: harperdb-${{ needs.getNodeVersion.outputs.harperdbVersion }}.tgz
        retention-days: 1