on:
  push:
    branches:
      - main
      - 'release_*'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
name: Build Studio
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Execute Build Script
        run: ./utility/devops/build/build-studio.sh