on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        submodules: recursive
    - name: Get package info
      id: package
      uses: codex-team/action-nodejs-package-info@v1
    #set integration test file_location
    - name: Update int env files_location
      run: echo "`jq --arg rootdir "$PWD/test/data/integrationTestsCsvs" '(.values[] | select(.key == "files_location") | .value) |= $rootdir' ./integrationTests/Int_test_env_var.json`" > ./integrationTests/Int_test_env_var.json
    # setup go
    - uses: actions/setup-node@v3
      with:
       node-version: ${{ steps.package.outputs.node }}
    # setup go
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.package.outputs.go-lang }}
    # add npm install
    - run: npm install --legacy-peer-deps
    # install harperdb
    - run: cd bin && node harperdb.js --TC_AGREEMENT yes --HDB_ROOT ${GITHUB_WORKSPACE}/hdb --HDB_ADMIN_USERNAME ${{secrets.HDB_ADMIN_USERNAME}} --HDB_ADMIN_PASSWORD ${{secrets.HDB_ADMIN_PASSWORD}} --NODE_NAME node1 --CLUSTERING_PORT 12345 --CLUSTERING_USER ${{secrets.CLUSTERING_USERNAME}} --CLUSTERING_PASSWORD ${{secrets.CLUSTERING_PASSWORD}} --CLUSTERING true --SERVER_PORT 9925 --CUSTOM_FUNCTIONS true --CLUSTERING_HUBSERVER_CLUSTER_NETWORK_PORT 12345
    # stop harperdb
    - run: cd bin && node harperdb.js stop
    # add npm test
    - run: npm test
    #- run: npm run integrationtests:source
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
