on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 12 * * 1-5'
  workflow_dispatch:
name: Run Build Package Cluster Test A
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  createInstances:
    needs:
      - build
    uses: ./.github/workflows/create-instances.yaml
    with:
      instanceCount: "5"
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
    secrets: inherit
  registerInstances:
    needs: 
      - createInstances
      - build
    uses: ./.github/workflows/install-and-register.yaml
    with:
      publicDns: ${{ needs.createInstances.outputs.publicDnsNames }}
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      nodeVersion: ${{ needs.build.outputs.nodeVersion }}
    secrets: inherit
  runTests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - createInstances
      - registerInstances
      - build
    steps:
    - name: Run Cluster Test A on Instances
      env:
        CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
      run: |
        #!/bin/bash

        cd ../
        echo "$CI_PRIVATE_KEY" > private_key && chmod 600 private_key

        public_dns_names="${{ needs.createInstances.outputs.publicDnsNames }}"
        public_ips="${{ needs.createInstances.outputs.publicIps }}"
        public_dns_names=($public_dns_names)
        public_ips=($public_ips)
        # Run the cluster tests from the first test VM
        public_dns_name="${public_dns_names[0]}"

        echo "Starting work on: $public_dns_name"

        ssh -i private_key -o ConnectTimeout=10 -o ConnectionAttempts=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR ubuntu@$public_dns_name \
          "sudo chmod +x /home/ubuntu/harperdb/test/ci-tests/cluster-test-a.sh && /home/ubuntu/harperdb/test/ci-tests/cluster-test-a.sh ${public_ips[@]} ${public_dns_names[@]}"
        echo "Ending work on: $public_dns_name"
  downloadLogs:
    if: always()
    needs: 
      - runTests
      - createInstances
    uses: ./.github/workflows/download-logs.yaml
    with:
      publicDns: ${{ needs.createInstances.outputs.publicDnsNames }}
    secrets: inherit
  destroyInstances:
    if: always()
    needs: downloadLogs
    uses: ./.github/workflows/destroy-instances.yaml
    with:
      instanceCount: "5"
    secrets: inherit   