on:
  workflow_dispatch:
name: DockerHub Publish Public
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  dockerBuild:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: "Setup Docker buildx"
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/download-artifact@v3
      with:
        name: harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz
        path: utility/Docker
    - name: "Build Docker Image and Publish"
      run: |
        cd utility/Docker
        docker buildx build \
          --build-arg NODE_VERSION=${{ needs.build.outputs.nodeVersion }} \
          --build-arg HARPERDB_TARBALL=harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz \
          --platform linux/amd64,linux/arm64 \
          --no-cache \
          --push \
          --tag harperdb/harperdb:latest \
          --tag harperdb/harperdb:${{ needs.build.outputs.harperdbVersion }} .
