on:
  workflow_call:
    inputs:
      harperdbVersion:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string
      dockerFile:
        required: false
        type: string
        default: 'utility/Docker/Dockerfile'
      dockerImage:
        required: false
        type: string
        default: 'harperdb/harperdb'
name: Docker Build
jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v3
    - name: "Setup Docker buildx"
      uses: docker/setup-buildx-action@v2
    - name: "Get Latest License Files"
      run: .github/scripts/get-license-files.sh
    - uses: actions/download-artifact@v3
      with:
        name: harperdb-${{ inputs.harperdbVersion }}.tgz
        path: ./
    - name: "Build Docker Image"
      env:
        HARPERDB_VERSION: ${{ inputs.harperdbVersion }}
        NODE_VERSION: ${{ inputs.nodeVersion }}
        DOCKERFILE: ${{ inputs.dockerFile }}
        DOCKER_IMAGE: ${{ inputs.dockerImage }}
        PUBLISH: "tar"
      run: .github/scripts/docker-publish.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: docker-harperdb_${{ inputs.harperdbVersion }}.tar
        path: docker-harperdb_${{ inputs.harperdbVersion }}.tar
        retention-days: 1