on:
  workflow_dispatch:
name: DockerHub Publish Public
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  dockerBuild:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: "Setup Docker buildx"
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/download-artifact@v3
      with:
        name: harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz
        path: ./
    - name: "Build Docker Image and Publish"
      env:
        HARPERDB_VERSION: ${{ needs.build.outputs.harperdbVersion }}
        NODE_VERSION: ${{ needs.build.outputs.nodeVersion }}
        PUBLISH: "public"
      run: ./.github/scripts/docker-publish.sh