name: DockerHub Publish Private

on:
  workflow_dispatch:
    inputs:
      tag_latest:
        description: 'tag this build as latest in registry'
        default: 'false'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  getLicenses:
    runs-on: gha-runner-scale-set
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: "Get Latest License Files"
      run: .github/scripts/get-license-files.sh
    - name: "Get HarperDB/harperdb_open_source_license_generator.git"
      uses: actions/checkout@v3
      with:
        repository: "HarperDB/harperdb_open_source_license_generator.git"
        path: "harperdb_open_source_license_generator"
        ref: "master"
    - uses: actions/setup-node@v3
    - name: "Generate license file"
      env:
        project_path: "."
        output_file: "utility/Docker/licenses/open-source-licenses-notices.md"
        template_file: "harperdb_open_source_license_generator/template.txt"
      run: |
        #!/usr/bin/env bash
        cd harperdb_open_source_license_generator
        npm install --omit=dev 
        cd -
        node harperdb_open_source_license_generator/index.js
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: "licenses"
        path: "utility/Docker/licenses/"
        retention-days: 1
  build-container-harperdb:
    needs:
      - build
      - getLicenses
    runs-on: gha-runner-scale-set
    timeout-minutes: 35
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: "Setup Docker buildx"
      uses: docker/setup-buildx-action@v3
      with:
        driver_opts: |
          network=host
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/download-artifact@v3
      with:
        name: harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz
        path: ./
    - uses: actions/download-artifact@v3
      with:
        name: "licenses"
        path: "utility/Docker/licenses/"
    - name: "Publish harperdb/private to Dockerhub"
      env:
        HARPERDB_VERSION: ${{ needs.build.outputs.harperdbVersion }}
        NODE_VERSION: ${{ needs.build.outputs.nodeVersion }}
        PUBLISH: "private"
        GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
        TAG_LATEST: "${{ inputs.tag_latest }}"
      run: ./.github/scripts/docker-publish.sh
      timeout-minutes: 30
