name: "Run All Docker Cluster Tests"

on:
#  push:
#    branches:
#      - main
#      - "release_*"
#  schedule:
#    - cron: '8 13 * * 1-5'
  workflow_dispatch:

jobs:
  ####################
  #  Build HarperDB
  ####################
  build:
    uses: ./.github/workflows/build.yaml

  ##########################
  #  Build Container Image
  ##########################
  dockerBuild:
    needs: build
    uses: ./.github/workflows/docker-build.yaml
    strategy:
      fail-fast: false
      matrix:
        file:
          - 'utility/Docker/Dockerfile'
          - 'utility/Docker/Dockerfile-openshift'
        include:
          - file: 'utility/Docker/Dockerfile'
            platform: 'linux/amd64'
            containerTarball: docker-harperdb_${{ inputs.harperdbVersion }}-standard-amd64-${{ github.run_number }}.tar
          - file: 'utility/Docker/Dockerfile'
            platform: 'linux/arm64'
            containerTarball: docker-harperdb_${{ inputs.harperdbVersion }}-standard-arm64-${{ github.run_number }}.tar
          - file: 'utility/Docker/Dockerfile-openshift'
            platform: 'linux/amd64'
            containerTarball: docker-harperdb_${{ inputs.harperdbVersion }}-openshift-amd64-${{ github.run_number }}.tar
          - file: 'utility/Docker/Dockerfile-openshift'
            platform: 'linux/arm64'
            containerTarball: docker-harperdb_${{ inputs.harperdbVersion }}-openshift-arm64-${{ github.run_number }}.tar
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      container: 'tar'
      containerTarball: ${{ matrtix.containerTarball }}
      file: ${{ matrix.file }}
      platforms: ${{ matrix.platform }}
      get_dummy_licenses: true

  ##############################
  #  Call Docker Test template
  #    cluster test a
  #############################
  cluster-test-a:
    needs:
      - build
      - dockerBuild
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        artifactSuffix:
          - '-standard-amd64-${{ github.run_number }}'
          - '-standard-arm64-${{ github.run_number }}'
          - '-openshift-amd64-${{ github.run_number }}'
          - '-openshift-arm64-${{ github.run_number }}'
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platform: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-a.sh'
    secrets: inherit

  ##############################
  #  Call Docker Test template
  #    cluster test b
  #############################
  cluster-test-b:
    needs:
      - build
      - dockerBuild
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        artifactSuffix:
          - '-standard-amd64-${{ github.run_number }}'
          - '-standard-arm64-${{ github.run_number }}'
          - '-openshift-amd64-${{ github.run_number }}'
          - '-openshift-arm64-${{ github.run_number }}'
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platform: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-b.sh'
    secrets: inherit

  ##############################
  #  Call Docker Test template
  #    cluster test c
  #############################
  cluster-test-c:
    needs:
      - build
      - dockerBuild
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        artifactSuffix:
          - '-standard-amd64-${{ github.run_number }}'
          - '-standard-arm64-${{ github.run_number }}'
          - '-openshift-amd64-${{ github.run_number }}'
          - '-openshift-arm64-${{ github.run_number }}'
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platform: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-c.sh'
    secrets: inherit

  #################################
  #  Send Slack Message on failure
  #################################
  sendSlackMessage:
    uses: ./.github/workflows/post-to-slack-channel.yaml
    if: ${{ failure() && (github.event_name == 'schedule' || github.event_name == 'push') }}
    secrets: inherit
    needs:
      - build
      - cluster-test-a
      - cluster-test-b
      - cluster-test-c
