name: "Run Docker Cluster Tests C"

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'list of container files to test'
        default: '["utility/Docker/Dockerfile","utility/Docker/Dockerfile-openshift"]'
        type: choice
        options:
          - '["utility/Docker/Dockerfile","utility/Docker/Dockerfile-openshift"]'
          - '["utility/Docker/Dockerfile"]'
          - '["utility/Docker/Dockerfile-openshift"]'
      platforms:
        description: 'list of platforms to test'
        default: '["amd64","arm64"]'
        type: choice
        options:
          - '["amd64","arm64"]'
          - '["amd64"]'
          - '["arm64"]'
  workflow_call:
    inputs:
      files:
        description: 'list of container files to test'
        default: '["utility/Docker/Dockerfile","utility/Docker/Dockerfile-openshift"]'
        type: string
      platforms:
        description: 'list of platforms to test'
        default: '["amd64","arm64"]'
        type: string

jobs:
  ####################
  #  Build HarperDB
  ####################
  build:
    uses: ./.github/workflows/build.yaml

  ##############################
  #  Call Docker Test template
  #    cluster test c
  #############################
  cluster-test-c:
    needs:
      - build
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(inputs.files) }}
        platform: ${{ fromJSON(inputs.platforms) }}
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platform: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-c.sh'
    secrets: inherit
