name: "Run Docker Cluster Tests B"

on:
  push:
    branches:
      - main
      - "release_*"
  schedule:
    - cron: '10 13 * * 1-5'
  workflow_dispatch:
  workflow_call:

jobs:
  ####################
  #  Build HarperDB
  ####################
  build:
    uses: ./.github/workflows/build.yaml

  ##############################
  #  Call Docker Test template
  #############################
  dockerBuild:
    needs:
      - build
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'harperdb/harperdb'
          - 'harperdb/harperdb-openshift'
        platform:
          - 'linux/amd64'
          - 'linux/arm64'
        include:
          - container: 'harperdb/harperdb'
            file: 'utility/Docker/Dockerfile'
          - container: 'harperdb/harperdb-openshift'
            file: 'utility/Docker/Dockerfile-openshift'
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platforms: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-b.sh'
