name: DockerHub Publish Private

on:
  workflow_dispatch:
    inputs:
      tag_latest:
        description: 'tag this build as latest in registry'
        default: 'false'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
#  build:
#    uses: ./.github/workflows/build.yaml
#  getLicenses:
#    runs-on: ubuntu-latest
#    #runs-on: fabric-dev-runner
#    timeout-minutes: 20
#    steps:
#    - uses: actions/checkout@v4
#    - name: "Get Latest License Files"
#      run: .github/scripts/get-license-files.sh
#    - name: "Get HarperDB/harperdb_open_source_license_generator.git"
#      uses: actions/checkout@v4
#      with:
#        repository: "HarperDB/harperdb_open_source_license_generator.git"
#        path: "harperdb_open_source_license_generator"
#        ref: "master"
#    - uses: actions/setup-node@v3
#    - name: "Generate license file"
#      env:
#        project_path: "."
#        output_file: "utility/Docker/licenses/open-source-licenses-notices.md"
#        template_file: "harperdb_open_source_license_generator/template.txt"
#      run: |
#        #!/usr/bin/env bash
#        cd harperdb_open_source_license_generator
#        npm install --omit=dev
#        cd -
#        node harperdb_open_source_license_generator/index.js
#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v3
#      with:
#        name: "licenses"
#        path: "utility/Docker/licenses/"
#        retention-days: 1
  build-container-harperdb:
#    needs:
#      - build
#      - getLicenses
    runs-on: ubuntu-latest
    #runs-on: fabric-dev-runner-dind
    timeout-minutes: 35
    outputs:
      nodeVersion: ${{ steps.getNode.outputs.NODE_VERSION }}
      harperdbVersion: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: "Setup Docker buildx"
      uses: docker/setup-buildx-action@v3
      with:
        driver_opts: |
          network=host
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#    - uses: actions/download-artifact@v3
#      with:
#        name: harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz
#        path: ./
#    - uses: actions/download-artifact@v3
#      with:
#        name: "licenses"
#        path: "utility/Docker/licenses/"

    - name: "Build and push harperdb/private"
      id: build-image
      timeout-minutes: 30
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./utility/Docker/Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: "harperdb/private:4.3.0-beta.2-${{ github.run_number }}"
        build-args: |
          NODE_VERSION=20
          HARPERDB_VERSION=${{ env.HARPERDB_VERSION }}
          VCS_REF=`git rev-parse HEAD`
          BUILD_DATE=`date -u +%FT%T
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
      env:
        HARPERDB_VERSION: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
        NODE_VERSION: ${{ steps.getNode.outputs.NODE_VERSION }}
        PUBLISH: "private"
        TAG_LATEST: "${{ inputs.tag_latest && 'latest' || '' }}"
