name: "Run Docker Cluster Tests B"

on:
  push:
    branches:
      - main
      - "release_*"
  schedule:
    - cron: '10 13 * * 1-5'
  workflow_dispatch:
    inputs:
      containers:
        description: 'list of containers to test'
        default: '["harperdb/harperdb","harperdb/harperdb-openshift"]'
        type: choice
        options:
          - '["harperdb/harperdb","harperdb/harperdb-openshift"]'
          - '["harperdb/harperdb"]'
          - '["harperdb/harperdb-openshift"]'
      platforms:
        description: 'list of platforms to test'
        default: '["linux/amd64","linux/arm64"]'
        type: choice
        options:
          - '["linux/amd64","linux/arm64"]'
          - '["linux/amd64"]'
          - '["linux/arm64"]'
  workflow_call:
    inputs:
      containers:
        description: 'list of containers to test'
        default: '["harperdb/harperdb","harperdb/harperdb-openshift"]'
        type: string
      platforms:
        description: 'list of platforms to test'
        default: '["linux/amd64","linux/arm64"]'
        type: string

jobs:
  ####################
  #  Build HarperDB
  ####################
  build:
    uses: ./.github/workflows/build.yaml

  ##############################
  #  Call Docker Test template
  #############################
  dockerBuild:
    needs:
      - build
    uses: ./.github/workflows/docker-cluster-test.yaml
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJSON(inputs.containers) }}
        platform: ${{ fromJSON(inputs.platforms) }}
        include:
          - container: 'harperdb/harperdb'
            file: 'utility/Docker/Dockerfile'
          - container: 'harperdb/harperdb-openshift'
            file: 'utility/Docker/Dockerfile-openshift'
    with:
      harperdbVersion: ${{ needs.build.outputs.harperdbVersion }}
      file: ${{ matrix.file }}
      platform: ${{ matrix.platform }}
      clusterTest: 'test/ci-tests/docker-cluster-test-b.sh'
