name: DockerHub Publish Private

on:
  workflow_dispatch:
    inputs:
      tag_latest:
        description: 'tag this build as latest in registry'
        default: 'false'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
#  build:
#    uses: ./.github/workflows/build.yaml
#  getLicenses:
#    runs-on: ubuntu-latest
#    #runs-on: fabric-dev-runner
#    timeout-minutes: 20
#    steps:
#    - uses: actions/checkout@v4
#    - name: "Get Latest License Files"
#      run: .github/scripts/get-license-files.sh
#    - name: "Get HarperDB/harperdb_open_source_license_generator.git"
#      uses: actions/checkout@v3
#      with:
#        repository: "HarperDB/harperdb_open_source_license_generator.git"
#        path: "harperdb_open_source_license_generator"
#        ref: "master"
#    - uses: actions/setup-node@v3
#    - name: "Generate license file"
#      env:
#        project_path: "."
#        output_file: "utility/Docker/licenses/open-source-licenses-notices.md"
#        template_file: "harperdb_open_source_license_generator/template.txt"
#      run: |
#        #!/usr/bin/env bash
#        cd harperdb_open_source_license_generator
#        npm install --omit=dev
#        cd -
#        node harperdb_open_source_license_generator/index.js
#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v3
#      with:
#        name: "licenses"
#        path: "utility/Docker/licenses/"
#        retention-days: 1
  build-container-harperdb:
#    needs:
#      - build
#      - getLicenses
    runs-on: ubuntu-latest
    #runs-on: fabric-dev-runner-dind
    timeout-minutes: 35
    outputs:
      nodeVersion: ${{ steps.getNode.outputs.NODE_VERSION }}
      harperdbVersion: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
    steps:
    - uses: actions/checkout@v4
#    - uses: actions/setup-node@v4
#      with:
#        node-version: 18
#    - id: getnode
#      name: Get node version
#      run: |
#        pwd
#        NODE_VERSION="$(node --version)"
#        NODE_VERSION="${NODE_VERSION:1}"
#        HARPERDB_VERSION=$(cat package.json | jq -r '.version')
#        echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
#        echo "HARPERDB_VERSION=$HARPERDB_VERSION" >> $GITHUB_OUTPUT
    # Checkout buildah action github repository
    - name: Checkout Buildah action
      uses: actions/checkout@v3
      with:
        path: "buildah-build"

    - name: Install latest buildah
      if: matrix.install_latest
      run: |
        bash buildah-build/.github/install_latest_buildah.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
#    - name: "Setup Docker buildx"
#      uses: docker/setup-buildx-action@v3
#      with:
#        driver_opts: |
#          network=host
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#    - uses: actions/download-artifact@v3
#      with:
#        name: harperdb-${{ needs.build.outputs.harperdbVersion }}.tgz
#        path: ./
#    - uses: actions/download-artifact@v3
#      with:
#        name: "licenses"
#        path: "utility/Docker/licenses/"
    - name: "Build harperdb/private image with buildah"
      id: build-image
      env:
        HARPERDB_VERSION: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
        NODE_VERSION: ${{ steps.getNode.outputs.NODE_VERSION }}
        PUBLISH: "private"
        GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
        TAG_LATEST: "${{ inputs.tag_latest }}"
      timeout-minutes: 30
      uses: redhat-actions/buildah-build@v2
      with:
        context: .
        containerfiles: |
          ./utility/Docker/Dockerfile
        platforms: linux/arm64, linux/amd64
        image: "harperdb/private"
        tags: "4.3.0-beta.2-${{ vars.GITHUB_RUN_NUMBER }}"
        build-args: |
          NODE_VERSION=18.19.0
          HARPERDB_VERSION=${{ env.HARPERDB_VERSION }}
          HARPERDB_TARBALL=harperdb-${{ env.HARPERDB_VERSION }}.tgz
          VCS_REF=`git rev-parse HEAD`
          BUILD_DATE=`date -u +%FT%T
    - name: Push to Dockerhub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#    - name: "Publish harperdb/private to Dockerhub"
#      env:
#        HARPERDB_VERSION: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
#        NODE_VERSION: ${{ steps.getNode.outputs.NODE_VERSION }}
#        PUBLISH: "private"
#        GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
#        TAG_LATEST: "${{ inputs.tag_latest }}"
#      #run: ./.github/scripts/docker-publish.sh
#      timeout-minutes: 30
#      # new stuff
#      uses: docker/build-push-action@v5
#      with:
#        context: .
#        file: utility/Docker/Dockerfile
#        platforms: linux/arm64
#        push: true
#        tags: "harperdb/private:4.3.0-beta.2-${{ vars.GITHUB_RUN_NUMBER }}"
#        build-args: |
#          "NODE_VERSION=${{ env.NODE_VERSION }}"
#          "HARPERDB_VERSION=${{ env.HARPERDB_VERSION }}"
#          "HARPERDB_TARBALL=harperdb-${{ env.HARPERDB_VERSION }}.tgz"
#          "VCS_REF=`git rev-parse HEAD`"
#          "BUILD_DATE=`date -u +%FT%T"
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
