on:
  workflow_dispatch:
name: Run All Docker Cluster Tests
jobs:
  runDockerClusterTestA:
    uses: ./.github/workflows/docker-cluster-test-a.yaml
    secrets: inherit
  runDockerClusterTestB:
    uses: ./.github/workflows/docker-cluster-test-b.yaml
    secrets: inherit
  runDockerClusterTestC:
    uses: ./.github/workflows/docker-cluster-test-c.yaml
    secrets: inherit
  runDockerClusterTestB:
    uses: ./.github/workflows/docker-cluster-test-b.yaml
  runDockerClusterTestC:
    uses: ./.github/workflows/docker-cluster-test-c.yaml
