on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Run Source Code CI Tests
jobs:
  getNodeVersion:
    runs-on: ubuntu-latest
    outputs:
      nodeVersion: ${{ steps.getNode.outputs.NODE_VERSION }}
      harperdbVersion: ${{ steps.getNode.outputs.HARPERDB_VERSION }}
      goVersion: ${{ steps.getNode.outputs.GO_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - id: getNode
      name: Get node version
      run: |
        pwd
        NODE_VERSION="$(cat package.json | jq -r '.engines.node')"
        HARPERDB_VERSION=$(cat package.json | jq -r '.version')
        GO_VERSION=$(cat package.json | jq -r '.engines."go-lang"')
        echo "::set-output name=NODE_VERSION::$NODE_VERSION"
        echo "::set-output name=HARPERDB_VERSION::$HARPERDB_VERSION"
        echo "::set-output name=GO_VERSION::$GO_VERSION"
  createInstances:
    outputs:
      publicDnsNames: ${{ steps.createInstances.outputs.PUBLIC_DNS_NAMES }}
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      with:
        terraform_wrapper: false
      uses: hashicorp/setup-terraform@v1
    - id: createInstances
      name: Create Instances
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
      run: |
        #!/bin/bash
        set -x
        cd ../
        mkdir terraform
        cd terraform
        echo "$CI_PRIVATE_KEY" > private_key && chmod 600 private_key
        mkdir upload
        cp ../harperdb/utility/devops/terraform/instance.tf .
        mv ../harperdb/utility/devops/scripts/user_data.sh .
        cp -r ../harperdb/ ./upload/

        terraform init
        terraform apply -var='private_key=./private_key' -var='region=us-east-2' -var='instance_count=1' -var='instance_name_prefix=GitHub-${{github.run_number}}' -var='instance_type=c5.2xlarge' -var='teamcity_buildconf_name=GitHub-${{github.run_number}}' -var='teamcity_build_number=GitHub-${{github.run_number}}' -var='volume_size=32' -auto-approve
        mapfile -t public_dns_names <<< $(terraform output -json | jq -r '.public_dns_names.value[]')
       
        echo "::set-output name=PUBLIC_DNS_NAMES::$public_dns_names"

        mkdir ../harperdb/tfstate/
        mv terraform.tfstate ../harperdb/tfstate/
        mv .terraform.lock.hcl ../harperdb/tfstate/
        mv instance.tf ../harperdb/tfstate/
    - name: 'Upload TFState'
      uses: actions/upload-artifact@v3
      with:
        name: tfstate
        path: tfstate/
        retention-days: 1
  registerInstances:
    needs: 
      - createInstances
      - getNodeVersion
    uses: ./.github/workflows/install-and-register.yaml
    with:
      publicDns: ${{ needs.createInstances.outputs.publicDnsNames }}
      harperdbVersion: ${{ needs.getNodeVersion.outputs.harperdbVersion }}
      goVersion: ${{ needs.getNodeVersion.outputs.goVersion }}
      nodeVersion: ${{ needs.getNodeVersion.outputs.nodeVersion }}
      installType: "sourceCode"
    secrets: inherit
  runTests:
    runs-on: ubuntu-latest
    needs:
      - createInstances
      - registerInstances
      - getNodeVersion
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests on Instances
      env:
        CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
      run: |
        #!/bin/bash

        cd ../
        echo "$CI_PRIVATE_KEY" > private_key && chmod 600 private_key
        public_dns_names=${{ needs.createInstances.outputs.publicDnsNames }}

        for public_dns_name in ${public_dns_names[@]}
        do 
        echo "Starting work on: $public_dns_name"
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR ubuntu@$public_dns_name << HERE
          . /home/ubuntu/.nvm/nvm.sh
          . /home/ubuntu/.nvm/bash_completion

          npm --loglevel=error install mocha -g
          cd /home/ubuntu/harperdb/bin/
          node harperdb.js stop
          npm test

          # Re-register HarperDB after unit tests
          cd /home/ubuntu/harperdb/utility/devops
          node register.js --reset_license --ram_allocation=16384

          cd /home/ubuntu/harperdb/bin/
          node harperdb.js
        HERE
        echo "Ending work on: $public_dns_name"
        done
      shell: bash
    - name: Run Integration Tests on Instances
      run: |
        #!/bin/bash
        cd ../
        public_dns_names=${{ needs.createInstances.outputs.publicDnsNames }}

        for public_dns_name in ${public_dns_names[@]}
        do 
        echo "Starting work on: $public_dns_name"
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR ubuntu@$public_dns_name << HERE
          . /home/ubuntu/.nvm/nvm.sh
          . /home/ubuntu/.nvm/bash_completion
          
          npm --loglevel=error install -g newman
          npm --loglevel=error install -g newman-reporter-teamcity
          npm --loglevel=error install -g newman-reporter-html
          npm --loglevel=error install -g newman-reporter-htmlextra

          cd /home/ubuntu/harperdb/integrationTests

          # Correct path to CSV files for integration tests
          sed -i 's/\/usr\/csv\//\/home\/ubuntu\/harperdb\/test\/data\/integrationTestsCsvs\//g' Int_test_env_var.json
          cat Int_test_env_var.json | grep "integrationTestsCsvs"

          newman run HarperDB_Integration_Tests.json -e Int_test_env_var.json --reporters teamcity,cli,html,htmlextra --reporter-html-export newman/report.html --reporter-htmlextra-export newman/extra_report.html --insecure
        HERE
        echo "Ending work on: $public_dns_name"
        done
      shell: bash
    - name: 'Download coverage file'
      run: |
        #!/bin/bash
        mkdir coverage
        cd ../
        public_dns_names=${{ needs.createInstances.outputs.publicDnsNames }}
        public_dns_name="${public_dns_names[0]}"
        scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/harperdb/coverage/lcov.info" "harperdb/coverage/lcov.info"
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      continue-on-error: true
    - name: Download Logs
      if: always()
      run: |
        #!/bin/bash
        cd ../
        mkdir logs-artifact
        public_dns_names=${{ needs.createInstances.outputs.publicDnsNames }}
        for public_dns_name in ${public_dns_names[@]}
        do 
          echo "Starting work on: $public_dns_name"
          mkdir logs-artifact/$public_dns_name
          scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/harperdb/integrationTests/newman/report.html" "logs-artifact/$public_dns_name/newman_report.html"
          scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/harperdb/integrationTests/newman/extra_report.html" "logs-artifact/$public_dns_name/newman_extra_report.html"
          scp -r -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/hdb/log/" "logs-artifact/$public_dns_name/"
          # 3.x
          if [[ "${{ needs.getNodeVersion.outputs.harperdbVersion }}" == 3* ]];
          then
            scp -r -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/hdb/config" "logs-artifact/$public_dns_name/"
          else
            # 4.x
            scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR "ubuntu@$public_dns_name:/home/ubuntu/hdb/harperdb.conf" "logs-artifact/$public_dns_name/harperdb.conf"
          fi
          echo "Ending work on: $public_dns_name"
        done
        mv logs-artifact harperdb
      shell: bash
    - name: 'Upload Log Artifact'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs-artifact/
        retention-days: 1
    - uses: actions/download-artifact@v3
      if: always()
      with:
        name: tfstate
        path: ../tfstate/
    - name: Setup Terraform
      if: always()
      with:
        terraform_wrapper: false
      uses: hashicorp/setup-terraform@v1
    - name: Destroy Instances
      if: always()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        #!/bin/bash
        cd ../tfstate
        terraform init
        # Terraform needs to validate this but doesn't need them to have real data to destroy
        mkdir upload
        touch user_data.sh
        terraform destroy -var='private_key=./private_key' -var='region=us-east-2' -var='instance_count=1' -var='instance_name_prefix=GitHub-${{github.run_number}}' -var='instance_type=c5.2xlarge' -var='teamcity_buildconf_name=GitHub-${{github.run_number}}' -var='teamcity_build_number=GitHub-${{github.run_number}}' -var='volume_size=32' -auto-approve
    