name: "Webflow - Update Open Source Licenses Page"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Whether to publish the page (true) or leave as draft (false)'
        required: true
        type: boolean
        default: false

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - name: "Get harperdb/harperdb_open_source_license_generator"
        uses: actions/checkout@v4
        with:
          repository: "HarperDB/harperdb_open_source_license_generator.git"
          path: "harperdb_open_source_license_generator"
          ref: "master"
      - uses: actions/setup-node@v4
      - name: "Generate license file"
        env:
          project_path: "."
          output_file: "open-source-licenses-notices.md"
          template_file: "harperdb_open_source_license_generator/template.txt"
        run: |
          #!/usr/bin/env bash
          cd harperdb_open_source_license_generator
          npm install --omit=dev 
          cd -
          node harperdb_open_source_license_generator/index.js
          cat open-source-licenses-notices.md

      - name: "Push Draft: open-source-licenses-notices"
        if: inputs.publish == false
        env:
          PUBLISH: false
          LICENSE_FILE: "open-source-licenses-notices.md"
          TOKEN: "${{ secrets.WEBFLOW_API_TOKEN }}"
        run: .github/scripts/webflow-upload-opensource-license.sh

      - name: "Push Live: open-source-licenses-notices"
        if: github.ref == 'refs/heads/main' || inputs.publish == true
        env:
          PUBLISH: true
          LICENSE_FILE: "open-source-licenses-notices.md"
          TOKEN: "${{ secrets.WEBFLOW_API_TOKEN }}"
        run: .github/scripts/webflow-upload-opensource-license.sh