name: "Webflow - Update Open Source Licenses Page"

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish the page (true) or leave as draft (false)'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      publish:
        description: 'Whether to publish the page (true) or leave as draft (false)'
        required: false
        type: boolean
        default: false

jobs:
  ####################
  #  Build HarperDB
  ####################
  # only if workflow_dispatch
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/build.yaml

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        if: ${{ github.event_name == 'workflow_call' }}
        with:
          name: "licenses"
          path: "utility/Docker/licenses/"

      - name: "Generate license files"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        continue-on-error: true
        uses: apache/skywalking-eyes/dependency@main
        with:
          mode: 'resolve'
          flags: '--output=utility/Docker/licenses'

      - name: "Push Draft: open-source-licenses-notices"
        if: inputs.publish == false
        env:
          PUBLISH: false
          LICENSE_FILE: "open-source-licenses-notices.md"
          TOKEN: "${{ secrets.WEBFLOW_API_TOKEN }}"
        run: .github/scripts/webflow-upload-opensource-license.sh

      - name: "Push Live: open-source-licenses-notices"
        if: github.ref == 'refs/heads/main' || inputs.publish == true
        env:
          PUBLISH: true
          LICENSE_FILE: "open-source-licenses-notices.md"
          TOKEN: "${{ secrets.WEBFLOW_API_TOKEN }}"
        run: .github/scripts/webflow-upload-opensource-license.sh